/// Build script for lupos — assembles `src/arch/x86/boot/header.S` with NASM and links it
/// into the kernel ELF.
///
/// Only runs the assembler when cross-compiling for the Lupos bare-metal target
/// (i.e., not during `cargo test` on the host).
use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

/// Convert `branding/splashart.png` to a flat binary of packed u32 pixels (0x00RRGGBB LE),
/// prefixed by [width: u32 LE, height: u32 LE].
///
/// Mirrors the conversion done by vendor/linux/drivers/video/logo/pnmtologo.c for the
/// Linux Tux logo.  The resulting file is `include_bytes!`-ed in logo.rs at compile time.
/// The embedded source is capped at 800 pixels wide because the graphical boot
/// path currently requests an 800×600 framebuffer.  The kernel scales it to
/// the actual framebuffer while preserving its aspect ratio.
fn generate_splash_bin(src: &str, dst: &PathBuf) {
    use image::GenericImageView;
    use image::imageops::FilterType;
    const MAX_W: u32 = 800;
    const MAX_H: u32 = 600;

    let img = match image::open(src) {
        Ok(i) => i,
        Err(e) => {
            // Non-fatal: emit an empty 1×1 black pixel so the kernel compiles without the
            // splash art rather than failing the entire build.
            eprintln!("build.rs: warning: failed to open {src}: {e}");
            let mut out = Vec::with_capacity(12);
            out.extend_from_slice(&1u32.to_le_bytes());
            out.extend_from_slice(&1u32.to_le_bytes());
            out.extend_from_slice(&0u32.to_le_bytes());
            fs::write(dst, &out).expect("failed to write fallback splash.bin");
            return;
        }
    };

    let (ow, oh) = img.dimensions();
    let (nw, nh) = if ow <= MAX_W && oh <= MAX_H {
        (ow, oh)
    } else if u64::from(MAX_W) * u64::from(oh) <= u64::from(MAX_H) * u64::from(ow) {
        (
            MAX_W,
            ((u64::from(oh) * u64::from(MAX_W)) / u64::from(ow)).max(1) as u32,
        )
    } else {
        (
            ((u64::from(ow) * u64::from(MAX_H)) / u64::from(oh)).max(1) as u32,
            MAX_H,
        )
    };
    // The dimensions above already preserve the aspect ratio.  `resize_exact`
    // avoids a second aspect-ratio calculation shaving off another pixel due
    // to integer rounding (the 1672×941 source should become exactly 800×450).
    let resized = img.resize_exact(nw, nh, FilterType::Lanczos3).to_rgba8();

    let mut out = Vec::with_capacity(8 + (nw * nh * 4) as usize);
    out.extend_from_slice(&nw.to_le_bytes());
    out.extend_from_slice(&nh.to_le_bytes());
    for pixel in resized.pixels() {
        let [r, g, b, a] = pixel.0;
        // Alpha-blend onto black background (pnmtologo.c uses opaque PPM; we handle RGBA).
        let r = ((r as u32 * a as u32 + 127) / 255) as u32;
        let g = ((g as u32 * a as u32 + 127) / 255) as u32;
        let b = ((b as u32 * a as u32 + 127) / 255) as u32;
        let packed: u32 = (r << 16) | (g << 8) | b;
        out.extend_from_slice(&packed.to_le_bytes());
    }
    fs::write(dst, &out).expect("failed to write splash.bin");
}

/// Extract Linux's exact 256-glyph VGA 8x16 font payload.
///
/// `fontdata_8x16.data` is expressed as one hexadecimal byte per C source
/// line. Keeping the generated binary tied to the vendored source avoids a
/// second, drifting hand-copied font table in the Rust port.
fn generate_linux_font_8x16_bin(src: &str, dst: &PathBuf) {
    const FONT_BYTES: usize = 256 * 16;

    let text = fs::read_to_string(src)
        .unwrap_or_else(|err| panic!("failed to read Linux VGA font source {src}: {err}"));
    let data_start = text
        .find("static const struct font_data fontdata_8x16")
        .unwrap_or_else(|| panic!("{src} does not define fontdata_8x16"));
    let data_end = text[data_start..]
        .find("const struct font_desc font_vga_8x16")
        .map(|offset| data_start + offset)
        .unwrap_or_else(|| panic!("{src} does not define font_vga_8x16"));

    let mut bytes = Vec::with_capacity(FONT_BYTES);
    for line in text[data_start..data_end].lines() {
        let token = line.trim_start();
        let Some(hex) = token.strip_prefix("0x") else {
            continue;
        };
        let Some(hex) = hex.split(',').next() else {
            continue;
        };
        if hex.len() != 2 || !hex.bytes().all(|byte| byte.is_ascii_hexdigit()) {
            continue;
        }
        bytes.push(
            u8::from_str_radix(hex, 16)
                .unwrap_or_else(|err| panic!("invalid font byte 0x{hex} in {src}: {err}")),
        );
    }

    assert_eq!(
        bytes.len(),
        FONT_BYTES,
        "{src} fontdata_8x16 must contain exactly {FONT_BYTES} bytes"
    );
    fs::write(dst, bytes).expect("failed to write linux-font-8x16.bin");
}

fn emit_linux_rustc_cfg() {
    // When generated by Kconfig's `--syncconfig`, Linux writes a file containing
    // the exact `--cfg=CONFIG_FOO` flags the kernel build would pass to Rust.
    //
    // We treat that file as the source of truth so Lupos can share the same
    // Kconfig semantics without inventing our own parser.
    let rustc_cfg = PathBuf::from("src/include/generated/rustc_cfg");
    println!("cargo:rerun-if-changed={}", rustc_cfg.display());
    println!("cargo:rerun-if-changed=.config");
    println!("cargo:rerun-if-changed=src/kernel/Kconfig");
    println!("cargo:rerun-if-changed=configs/lupos_defconfig");
    println!("cargo:rerun-if-changed=Makefile");

    // Raw `cargo build/test -p lupos` must honor the same configuration as
    // the Makefile and xtask entry points. `syncconfig` is a Kconfig-only
    // target (it never invokes Cargo), so calling it here cannot recurse.
    let status = Command::new("make")
        .arg("syncconfig")
        .status()
        .expect("failed to run `make syncconfig` from build.rs");
    assert!(
        status.success(),
        "`make syncconfig` failed; Lupos refuses to compile without synchronized Kconfig output"
    );

    let text = fs::read_to_string(&rustc_cfg).unwrap_or_else(|err| {
        panic!(
            "Kconfig synchronization did not produce {}: {err}",
            rustc_cfg.display()
        )
    });

    for line in text.lines() {
        let line = line.trim();
        if let Some(cfg) = line.strip_prefix("--cfg=") {
            if !cfg.is_empty() {
                println!("cargo:rustc-cfg={cfg}");
            }
        }
    }
}

fn main() {
    let target = env::var("TARGET").unwrap_or_default();
    emit_linux_rustc_cfg();

    // Generate splash pixel data from branding/splashart.png — runs on every host target
    // (including cargo test) so the env var LUPOS_SPLASH_BIN is always set.
    // Reference: vendor/linux/drivers/video/logo/pnmtologo.c
    println!("cargo:rerun-if-changed=branding/splashart.png");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let splash_bin = out_dir.join("splash.bin");
    // Cargo reruns this script when either the source image or build.rs changes.
    // Always rewrite the derived bytes so an older OUT_DIR cannot retain the
    // former 320×180 image after the sizing policy changes.
    generate_splash_bin("branding/splashart.png", &splash_bin);
    println!("cargo:rustc-env=LUPOS_SPLASH_BIN={}", splash_bin.display());

    let font_src = "vendor/linux/lib/fonts/font_8x16.c";
    let font_bin = out_dir.join("linux-font-8x16.bin");
    println!("cargo:rerun-if-changed={font_src}");
    generate_linux_font_8x16_bin(font_src, &font_bin);
    println!("cargo:rustc-env=LUPOS_FONT_8X16_BIN={}", font_bin.display());

    // Only assemble src/arch/x86/boot/header.S when targeting the Lupos
    // bare-metal target. Host unit tests do not need the boot object.
    if target == "x86_64-lupos" {
        let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

        // ── src/arch/x86/boot/header.S: Linux boot-protocol 32→64-bit transition (ELF64 object) ──
        let asm_source = "src/arch/x86/boot/header.S";
        let boot_obj = out_dir.join("boot.o");

        let status = Command::new("nasm")
            .args(["-f", "elf64", "-o"])
            .arg(&boot_obj)
            .arg(asm_source)
            .status()
            .expect("failed to run nasm; install it with your Linux package manager");

        assert!(status.success(), "nasm failed to assemble {asm_source}");

        println!("cargo:rustc-link-arg={}", boot_obj.display());
        println!("cargo:rerun-if-changed={asm_source}");

        // ── src/arch/x86/realmode/rm/trampoline_64.S: AP startup trampoline (flat binary, embedded via include_bytes!) ──
        //
        // The AP trampoline runs at physical address 0x8000 in 16-bit real mode.
        // It cannot be an ELF object (no relocations at 0x8000); instead we assemble
        // it as a flat binary and embed it in the kernel via include_bytes!().
        //
        // The BSP copies this binary to 0x8000 at runtime before sending SIPI.
        //
        // Reference: Intel SDM Vol. 3A §10.6.7 "MP Initialization Protocol"
        let ap_boot_src = "src/arch/x86/realmode/rm/trampoline_64.S";
        let ap_boot_bin = out_dir.join("ap_boot.bin");

        let status = Command::new("nasm")
            .args(["-f", "bin", "-o"])
            .arg(&ap_boot_bin)
            .arg(ap_boot_src)
            .status()
            .expect(
                "failed to run nasm for src/arch/x86/realmode/rm/trampoline_64.S — is nasm installed?",
            );

        assert!(status.success(), "nasm failed to assemble {ap_boot_src}");

        // Export the path so smp.rs can embed it with:
        //   static AP_BOOT_CODE: &[u8] = include_bytes!(env!("AP_BOOT_BIN"));
        println!("cargo:rustc-env=AP_BOOT_BIN={}", ap_boot_bin.display());
        println!("cargo:rerun-if-changed={ap_boot_src}");
    }

    println!("cargo:rerun-if-changed=src/arch/x86/kernel/vmlinux.lds.S");
}
