#!/usr/bin/env bash
set -euo pipefail

KCONFIG_CONF="${KCONFIG_CONF:-vendor/linux/scripts/kconfig/conf}"
KCONFIG="${KCONFIG:-kernel/Kconfig}"
DEFCONFIG="${DEFCONFIG:-configs/lupos_defconfig}"

# Detection matrix audit trail:
# CONFIG_PCI=y
# CONFIG_ACPI=y
# CONFIG_FRAMEBUFFER=y
# CONFIG_DRM=y
# CONFIG_AGP=m
# CONFIG_AGP_AMD64=m
# CONFIG_AGP_INTEL=m
# CONFIG_DRM_I915=m
# CONFIG_DRM_VIRTIO_GPU=m
# CONFIG_USB_XHCI=y
# CONFIG_HID=y
# CONFIG_SOUND=y
# CONFIG_SND_HDA_INTEL=y
# CONFIG_VIRTIO_PCI_LIB=m
# CONFIG_VIRTIO_PCI=m
# CONFIG_VIRTIO_BLK=m
# CONFIG_VIRTIO_NET=m
# CONFIG_E1000=m

detect="$(mktemp)"
tmp="$(mktemp)"
generated_dump=""
cleanup() {
	rm -f "$detect" "$tmp"
	if [ -n "$generated_dump" ]; then
		rm -f "$generated_dump"
	fi
}
trap cleanup EXIT

if [ -n "${LUPOS_LSPCI_DUMP:-}" ] && [ -f "$LUPOS_LSPCI_DUMP" ]; then
	cat "$LUPOS_LSPCI_DUMP" >> "$detect"
elif command -v lspci >/dev/null 2>&1; then
	generated_dump="$(mktemp)"
	lspci -nn > "$generated_dump"
	cat "$generated_dump" >> "$detect"
fi

if [ -n "${LUPOS_ACPI_DUMP:-}" ] && [ -f "$LUPOS_ACPI_DUMP" ]; then
	cat "$LUPOS_ACPI_DUMP" >> "$detect"
fi
if [ -n "${LUPOS_DMI_DUMP:-}" ] && [ -f "$LUPOS_DMI_DUMP" ]; then
	cat "$LUPOS_DMI_DUMP" >> "$detect"
fi

for dmi_file in /sys/class/dmi/id/sys_vendor /sys/class/dmi/id/product_name /sys/class/dmi/id/board_name; do
	if [ -r "$dmi_file" ]; then
		cat "$dmi_file" >> "$detect"
	fi
done

if [ ! -s "$detect" ]; then
	echo "*** localmodconfig: no PCI/ACPI/DMI evidence available; falling back to $DEFCONFIG"
	"$KCONFIG_CONF" --defconfig="$DEFCONFIG" "$KCONFIG"
	"$KCONFIG_CONF" --syncconfig "$KCONFIG"
	exit 0
fi

emit() {
	local symbol="$1"
	sed -i -e "/^CONFIG_${symbol}=/d" -e "/^# CONFIG_${symbol} is not set$/d" "$tmp"
	if ! grep -qx "CONFIG_${symbol}=y" "$tmp"; then
		echo "CONFIG_${symbol}=y" >> "$tmp"
	fi
}

emit_module() {
	local symbol="$1"
	sed -i -e "/^CONFIG_${symbol}=/d" -e "/^# CONFIG_${symbol} is not set$/d" "$tmp"
	if ! grep -qx "CONFIG_${symbol}=m" "$tmp"; then
		echo "CONFIG_${symbol}=m" >> "$tmp"
	fi
}

has() {
	grep -qiE "$1" "$detect"
}

{
	echo "# Auto-generated by 'make localmodconfig'"
	echo "CONFIG_MODULES=y"
	echo "# CONFIG_AGP is not set"
	echo "# CONFIG_AGP_AMD64 is not set"
	echo "# CONFIG_AGP_INTEL is not set"
	echo "# CONFIG_DRM_I915 is not set"
	echo "# CONFIG_DRM_VIRTIO_GPU is not set"
} > "$tmp"

if has "PCI bridge|PCI host|PCI Express|PCIe|PNP0A03|PNP0A08|MCFG|8086:|1af4:|10ec:|1022:|1002:|qemu|bochs|kvm|vmware"; then
	emit PCI
fi

if has "ACPI|PNP0A03|PNP0A08|MCFG|APIC|HPET|qemu|bochs|kvm"; then
	emit ACPI
fi

if has "IOMMU|DMAR|AMD-Vi|Intel-IOMMU|VT-d"; then
	emit IOMMU
	emit PCI
fi

if has "16550|8250|serial|COM[0-9]|PNP0501|qemu|bochs|kvm"; then
	emit SERIAL_8250
fi

if has "VGA|Display|0300|Framebuffer|Bochs|QXL|virtio.*gpu|qemu|bochs|kvm|vmware"; then
	emit FRAMEBUFFER
	emit DRM
fi

if has "VGA.*Intel|Display.*Intel|Intel.*(VGA|Display|Graphics)"; then
	emit PCI
	emit FRAMEBUFFER
	emit DRM
	emit_module AGP
	emit_module AGP_INTEL
	emit_module DRM_I915
fi

if has "VGA.*AMD|Display.*AMD|AMD.*(VGA|Display|Graphics)|1002:"; then
	emit PCI
	emit FRAMEBUFFER
	emit DRM
	emit_module AGP
	emit_module AGP_AMD64
fi

if has "virtio.*(gpu|vga)|(gpu|vga).*virtio|1af4:1050"; then
	emit PCI
	emit FRAMEBUFFER
	emit DRM
	emit VIRTIO
	emit_module DRM_VIRTIO_GPU
fi

if has "USB|xHCI|EHCI|OHCI|UHCI|0c03"; then
	emit USB
	emit PCI
fi

if has "xHCI|0c03:30|USB controller.*xHCI|8086:.*USB|1022:.*USB"; then
	emit USB
	emit USB_XHCI
	emit PCI
fi

if has "HID|Keyboard|Mouse|Touchpad|Input|USB"; then
	emit INPUT
	emit HID
fi

if has "Audio|HDA|HD Audio|0403|ICH9|Intel.*Audio|qemu|bochs|kvm"; then
	emit PCI
	emit SOUND
	emit SND_HDA_INTEL
fi

if has "virtio|1af4:|qemu|bochs|kvm"; then
	emit PCI
	emit VIRTIO
	emit_module VIRTIO_PCI_LIB
	emit_module VIRTIO_PCI
fi

if has "virtio.*(net|network|ethernet)|(net|network|ethernet).*virtio|1af4:(1000|1041)|qemu|bochs|kvm"; then
	emit NET
	emit NETDEVICES
	emit_module VIRTIO_NET
fi

if has "virtio.*(blk|block|storage|scsi)|(blk|block|storage|scsi).*virtio|1af4:(1001|1042)|qemu|bochs|kvm"; then
	emit_module VIRTIO_BLK
fi

if has "Intel.*(8254|e1000|PRO/1000)|Ethernet controller.*8086:(100e|100f|1010|1011|1012|1013|1015|1016|1017|1018|1019|101a|101d|1026|1027|1028|1075|1076|1077|1078|1079|107a|107b|107c|108a|1099|10b5)|8086:(100e|100f|1010|1011|1012|1013|1015|1016|1017|1018|1019|101a|101d|1026|1027|1028|1075|1076|1077|1078|1079|107a|107b|107c|108a|1099|10b5)"; then
	emit PCI
	emit NET
	emit NETDEVICES
	emit_module E1000
fi

echo "*** localmodconfig: writing .config from detected PCI/ACPI/DMI devices"
"$KCONFIG_CONF" --defconfig="$tmp" "$KCONFIG"
"$KCONFIG_CONF" --syncconfig "$KCONFIG"
