// SPDX-License-Identifier: GPL-2.0-only
//! linux-source: arch/x86/include/uapi/asm/vmx.h
//! linux-revision: 425f94c2954b1fe80ebdbf9b29854e89750355df
//! architectures: x86_64
//! rewrite-task: S000805

// Copyright (c) 2004, Intel Corporation.
// Copyright (C) 2006 Qumranet.

pub const VMX_EXIT_REASONS_FAILED_VMENTRY: u32 = 0x8000_0000;
pub const VMX_EXIT_REASONS_SGX_ENCLAVE_MODE: i32 = 0x0800_0000;

pub const EXIT_REASON_EXCEPTION_NMI: i32 = 0;
pub const EXIT_REASON_EXTERNAL_INTERRUPT: i32 = 1;
pub const EXIT_REASON_TRIPLE_FAULT: i32 = 2;
pub const EXIT_REASON_INIT_SIGNAL: i32 = 3;
pub const EXIT_REASON_SIPI_SIGNAL: i32 = 4;
pub const EXIT_REASON_OTHER_SMI: i32 = 6;
pub const EXIT_REASON_INTERRUPT_WINDOW: i32 = 7;
pub const EXIT_REASON_NMI_WINDOW: i32 = 8;
pub const EXIT_REASON_TASK_SWITCH: i32 = 9;
pub const EXIT_REASON_CPUID: i32 = 10;
pub const EXIT_REASON_HLT: i32 = 12;
pub const EXIT_REASON_INVD: i32 = 13;
pub const EXIT_REASON_INVLPG: i32 = 14;
pub const EXIT_REASON_RDPMC: i32 = 15;
pub const EXIT_REASON_RDTSC: i32 = 16;
pub const EXIT_REASON_VMCALL: i32 = 18;
pub const EXIT_REASON_VMCLEAR: i32 = 19;
pub const EXIT_REASON_VMLAUNCH: i32 = 20;
pub const EXIT_REASON_VMPTRLD: i32 = 21;
pub const EXIT_REASON_VMPTRST: i32 = 22;
pub const EXIT_REASON_VMREAD: i32 = 23;
pub const EXIT_REASON_VMRESUME: i32 = 24;
pub const EXIT_REASON_VMWRITE: i32 = 25;
pub const EXIT_REASON_VMOFF: i32 = 26;
pub const EXIT_REASON_VMON: i32 = 27;
pub const EXIT_REASON_CR_ACCESS: i32 = 28;
pub const EXIT_REASON_DR_ACCESS: i32 = 29;
pub const EXIT_REASON_IO_INSTRUCTION: i32 = 30;
pub const EXIT_REASON_MSR_READ: i32 = 31;
pub const EXIT_REASON_MSR_WRITE: i32 = 32;
pub const EXIT_REASON_INVALID_STATE: i32 = 33;
pub const EXIT_REASON_MSR_LOAD_FAIL: i32 = 34;
pub const EXIT_REASON_MWAIT_INSTRUCTION: i32 = 36;
pub const EXIT_REASON_MONITOR_TRAP_FLAG: i32 = 37;
pub const EXIT_REASON_MONITOR_INSTRUCTION: i32 = 39;
pub const EXIT_REASON_PAUSE_INSTRUCTION: i32 = 40;
pub const EXIT_REASON_MCE_DURING_VMENTRY: i32 = 41;
pub const EXIT_REASON_TPR_BELOW_THRESHOLD: i32 = 43;
pub const EXIT_REASON_APIC_ACCESS: i32 = 44;
pub const EXIT_REASON_EOI_INDUCED: i32 = 45;
pub const EXIT_REASON_GDTR_IDTR: i32 = 46;
pub const EXIT_REASON_LDTR_TR: i32 = 47;
pub const EXIT_REASON_EPT_VIOLATION: i32 = 48;
pub const EXIT_REASON_EPT_MISCONFIG: i32 = 49;
pub const EXIT_REASON_INVEPT: i32 = 50;
pub const EXIT_REASON_RDTSCP: i32 = 51;
pub const EXIT_REASON_PREEMPTION_TIMER: i32 = 52;
pub const EXIT_REASON_INVVPID: i32 = 53;
pub const EXIT_REASON_WBINVD: i32 = 54;
pub const EXIT_REASON_XSETBV: i32 = 55;
pub const EXIT_REASON_APIC_WRITE: i32 = 56;
pub const EXIT_REASON_RDRAND: i32 = 57;
pub const EXIT_REASON_INVPCID: i32 = 58;
pub const EXIT_REASON_VMFUNC: i32 = 59;
pub const EXIT_REASON_ENCLS: i32 = 60;
pub const EXIT_REASON_RDSEED: i32 = 61;
pub const EXIT_REASON_PML_FULL: i32 = 62;
pub const EXIT_REASON_XSAVES: i32 = 63;
pub const EXIT_REASON_XRSTORS: i32 = 64;
pub const EXIT_REASON_UMWAIT: i32 = 67;
pub const EXIT_REASON_TPAUSE: i32 = 68;
pub const EXIT_REASON_BUS_LOCK: i32 = 74;
pub const EXIT_REASON_NOTIFY: i32 = 75;
pub const EXIT_REASON_SEAMCALL: i32 = 76;
pub const EXIT_REASON_TDCALL: i32 = 77;
pub const EXIT_REASON_MSR_READ_IMM: i32 = 84;
pub const EXIT_REASON_MSR_WRITE_IMM: i32 = 85;

#[macro_export]
macro_rules! VMX_EXIT_REASONS {
    () => {
        [
            (EXIT_REASON_EXCEPTION_NMI, "EXCEPTION_NMI"),
            (EXIT_REASON_EXTERNAL_INTERRUPT, "EXTERNAL_INTERRUPT"),
            (EXIT_REASON_TRIPLE_FAULT, "TRIPLE_FAULT"),
            (EXIT_REASON_INIT_SIGNAL, "INIT_SIGNAL"),
            (EXIT_REASON_SIPI_SIGNAL, "SIPI_SIGNAL"),
            (EXIT_REASON_INTERRUPT_WINDOW, "INTERRUPT_WINDOW"),
            (EXIT_REASON_NMI_WINDOW, "NMI_WINDOW"),
            (EXIT_REASON_TASK_SWITCH, "TASK_SWITCH"),
            (EXIT_REASON_CPUID, "CPUID"),
            (EXIT_REASON_HLT, "HLT"),
            (EXIT_REASON_INVD, "INVD"),
            (EXIT_REASON_INVLPG, "INVLPG"),
            (EXIT_REASON_RDPMC, "RDPMC"),
            (EXIT_REASON_RDTSC, "RDTSC"),
            (EXIT_REASON_VMCALL, "VMCALL"),
            (EXIT_REASON_VMCLEAR, "VMCLEAR"),
            (EXIT_REASON_VMLAUNCH, "VMLAUNCH"),
            (EXIT_REASON_VMPTRLD, "VMPTRLD"),
            (EXIT_REASON_VMPTRST, "VMPTRST"),
            (EXIT_REASON_VMREAD, "VMREAD"),
            (EXIT_REASON_VMRESUME, "VMRESUME"),
            (EXIT_REASON_VMWRITE, "VMWRITE"),
            (EXIT_REASON_VMOFF, "VMOFF"),
            (EXIT_REASON_VMON, "VMON"),
            (EXIT_REASON_CR_ACCESS, "CR_ACCESS"),
            (EXIT_REASON_DR_ACCESS, "DR_ACCESS"),
            (EXIT_REASON_IO_INSTRUCTION, "IO_INSTRUCTION"),
            (EXIT_REASON_MSR_READ, "MSR_READ"),
            (EXIT_REASON_MSR_WRITE, "MSR_WRITE"),
            (EXIT_REASON_INVALID_STATE, "INVALID_STATE"),
            (EXIT_REASON_MSR_LOAD_FAIL, "MSR_LOAD_FAIL"),
            (EXIT_REASON_MWAIT_INSTRUCTION, "MWAIT_INSTRUCTION"),
            (EXIT_REASON_MONITOR_TRAP_FLAG, "MONITOR_TRAP_FLAG"),
            (EXIT_REASON_MONITOR_INSTRUCTION, "MONITOR_INSTRUCTION"),
            (EXIT_REASON_PAUSE_INSTRUCTION, "PAUSE_INSTRUCTION"),
            (EXIT_REASON_MCE_DURING_VMENTRY, "MCE_DURING_VMENTRY"),
            (EXIT_REASON_TPR_BELOW_THRESHOLD, "TPR_BELOW_THRESHOLD"),
            (EXIT_REASON_APIC_ACCESS, "APIC_ACCESS"),
            (EXIT_REASON_EOI_INDUCED, "EOI_INDUCED"),
            (EXIT_REASON_GDTR_IDTR, "GDTR_IDTR"),
            (EXIT_REASON_LDTR_TR, "LDTR_TR"),
            (EXIT_REASON_EPT_VIOLATION, "EPT_VIOLATION"),
            (EXIT_REASON_EPT_MISCONFIG, "EPT_MISCONFIG"),
            (EXIT_REASON_INVEPT, "INVEPT"),
            (EXIT_REASON_RDTSCP, "RDTSCP"),
            (EXIT_REASON_PREEMPTION_TIMER, "PREEMPTION_TIMER"),
            (EXIT_REASON_INVVPID, "INVVPID"),
            (EXIT_REASON_WBINVD, "WBINVD"),
            (EXIT_REASON_XSETBV, "XSETBV"),
            (EXIT_REASON_APIC_WRITE, "APIC_WRITE"),
            (EXIT_REASON_RDRAND, "RDRAND"),
            (EXIT_REASON_INVPCID, "INVPCID"),
            (EXIT_REASON_VMFUNC, "VMFUNC"),
            (EXIT_REASON_ENCLS, "ENCLS"),
            (EXIT_REASON_RDSEED, "RDSEED"),
            (EXIT_REASON_PML_FULL, "PML_FULL"),
            (EXIT_REASON_XSAVES, "XSAVES"),
            (EXIT_REASON_XRSTORS, "XRSTORS"),
            (EXIT_REASON_UMWAIT, "UMWAIT"),
            (EXIT_REASON_TPAUSE, "TPAUSE"),
            (EXIT_REASON_BUS_LOCK, "BUS_LOCK"),
            (EXIT_REASON_NOTIFY, "NOTIFY"),
            (EXIT_REASON_TDCALL, "TDCALL"),
            (EXIT_REASON_MSR_READ_IMM, "MSR_READ_IMM"),
            (EXIT_REASON_MSR_WRITE_IMM, "MSR_WRITE_IMM"),
        ]
    };
}

#[macro_export]
macro_rules! VMX_EXIT_REASON_FLAGS {
    () => {
        [(VMX_EXIT_REASONS_FAILED_VMENTRY, "FAILED_VMENTRY")]
    };
}

pub const VMX_ABORT_SAVE_GUEST_MSR_FAIL: i32 = 1;
pub const VMX_ABORT_LOAD_HOST_PDPTE_FAIL: i32 = 2;
pub const VMX_ABORT_LOAD_HOST_MSR_FAIL: i32 = 4;
