//! linux-parity: complete
//! linux-source: vendor/linux/kernel/trace
//! test-origin: linux:vendor/linux/kernel/trace
//! Static tracepoints — Linux's `TRACE_EVENT` mechanism.
//!
//! Mirrors the design of `vendor/linux/include/linux/tracepoint.h`:
//! each tracepoint is a static instance with an `enabled` flag (cheap check
//! at the call site, branch is predicted not-taken when disabled), a fixed
//! probe table, and a typed `fire()` function generated by the macro.
//!
//! Lupos simplifications versus Linux:
//! - No `static_branch_unlikely` / `static_key` — we use a plain `AtomicBool`.
//!   The cost of a single-cache-line load is acceptable in M62.
//! - Probe table is a fixed-size array of `TracepointProbe` slots (max 8 per
//!   tracepoint).  Linux uses an RCU-managed dynamic array; ours is static.
//! - No SRCU / RCU sync at register/unregister; we hold a spinlock.
//!
//! Refs:
//! - `vendor/linux/kernel/tracepoint.c::tracepoint_probe_register`
//! - `vendor/linux/include/linux/tracepoint.h::DEFINE_TRACE`

use core::sync::atomic::{AtomicBool, AtomicUsize, Ordering};

use spin::Mutex;

pub const MAX_PROBES_PER_TRACEPOINT: usize = 8;

/// A single registered probe.  Untyped — the macro casts to the typed
/// signature at fire() time.
#[derive(Clone, Copy)]
pub struct TracepointProbe {
    pub func: usize, // function pointer (cast to typed fn at use)
    pub data: usize, // optional context word
}

/// Static state for one tracepoint.
pub struct Tracepoint {
    pub name: &'static str,
    pub enabled: AtomicBool,
    pub probe_count: AtomicUsize,
    pub probes: Mutex<[TracepointProbe; MAX_PROBES_PER_TRACEPOINT]>,
}

impl Tracepoint {
    pub const fn new(name: &'static str) -> Self {
        Self {
            name,
            enabled: AtomicBool::new(false),
            probe_count: AtomicUsize::new(0),
            probes: Mutex::new([TracepointProbe { func: 0, data: 0 }; MAX_PROBES_PER_TRACEPOINT]),
        }
    }

    /// Register a probe.  Returns Err(-ENOSPC) if the table is full.
    /// Mirrors `tracepoint_probe_register`.
    pub fn register(&self, probe: TracepointProbe) -> Result<(), i32> {
        let mut g = self.probes.lock();
        let n = self.probe_count.load(Ordering::Acquire);
        if n >= MAX_PROBES_PER_TRACEPOINT {
            return Err(-28); // ENOSPC
        }
        g[n] = probe;
        self.probe_count.store(n + 1, Ordering::Release);
        self.enabled.store(true, Ordering::Release);
        Ok(())
    }

    pub fn unregister(&self, func: usize) -> Result<(), i32> {
        let mut g = self.probes.lock();
        let n = self.probe_count.load(Ordering::Acquire);
        let mut idx = None;
        for i in 0..n {
            if g[i].func == func {
                idx = Some(i);
                break;
            }
        }
        let i = match idx {
            Some(i) => i,
            None => return Err(-2), // ENOENT
        };
        // Compact down.
        for j in i..n - 1 {
            g[j] = g[j + 1];
        }
        g[n - 1] = TracepointProbe { func: 0, data: 0 };
        let new_n = n - 1;
        self.probe_count.store(new_n, Ordering::Release);
        if new_n == 0 {
            self.enabled.store(false, Ordering::Release);
        }
        Ok(())
    }

    /// Fire the tracepoint by calling all registered probes.
    /// The `T` type is whatever the caller's macro expands to — typically a
    /// fn pointer with a fixed signature.
    ///
    /// SAFETY: caller must ensure the registered probe `func` field is a
    /// valid `T` cast; the `tracepoint!` macro guarantees this.
    pub fn fire_with(&self, mut callback: impl FnMut(usize, usize)) {
        if !self.enabled.load(Ordering::Acquire) {
            return;
        }
        let g = self.probes.lock();
        let n = self.probe_count.load(Ordering::Acquire);
        for i in 0..n {
            callback(g[i].func, g[i].data);
        }
    }

    pub fn probe_count_now(&self) -> usize {
        self.probe_count.load(Ordering::Acquire)
    }
}

// Tracepoints are declared explicitly: `static FOO: Tracepoint = Tracepoint::new("foo");`
// and fired via a typed `fn trace_foo(...)` wrapper that calls `FOO.fire_with(...)`.
// A `tracepoint!()` macro for typed-signature codegen is deferred — manual
// declaration is sufficient until M63 needs many tracepoints in one pass.

#[cfg(test)]
mod tests {
    use super::*;
    use core::sync::atomic::{AtomicU32, Ordering};

    static TEST_TP: Tracepoint = Tracepoint::new("test_tp");

    static FIRED_COUNT: AtomicU32 = AtomicU32::new(0);
    static LAST_VALUE: AtomicU32 = AtomicU32::new(0);

    fn probe_fn(v: u32, _data: usize) {
        FIRED_COUNT.fetch_add(1, Ordering::Relaxed);
        LAST_VALUE.store(v, Ordering::Relaxed);
    }

    #[test]
    fn disabled_when_no_probes_registered() {
        let tp = Tracepoint::new("z");
        assert!(!tp.enabled.load(Ordering::Acquire));
    }

    #[test]
    fn register_enables_and_fire_calls_probe() {
        FIRED_COUNT.store(0, Ordering::Relaxed);
        TEST_TP
            .register(TracepointProbe {
                func: probe_fn as usize,
                data: 0,
            })
            .unwrap();
        assert!(TEST_TP.enabled.load(Ordering::Acquire));

        TEST_TP.fire_with(|func, data| {
            let f: fn(u32, usize) = unsafe { core::mem::transmute(func) };
            f(99, data);
        });
        assert_eq!(FIRED_COUNT.load(Ordering::Relaxed), 1);
        assert_eq!(LAST_VALUE.load(Ordering::Relaxed), 99);

        TEST_TP.unregister(probe_fn as usize).unwrap();
        assert!(!TEST_TP.enabled.load(Ordering::Acquire));
    }

    #[test]
    fn capacity_full_returns_enospc() {
        let tp = Tracepoint::new("cap");
        for _ in 0..MAX_PROBES_PER_TRACEPOINT {
            tp.register(TracepointProbe {
                func: 0xdead,
                data: 0,
            })
            .unwrap();
        }
        assert_eq!(tp.register(TracepointProbe { func: 1, data: 0 }), Err(-28));
    }
}
