//! linux-parity: complete
//! linux-source: vendor/linux/certs
//! test-origin: linux:vendor/linux/certs
//! Certificate and blacklist source coverage.

pub mod blacklist;
pub mod blacklist_hashes;
pub mod extract_cert;
pub mod system_keyring;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CertsSourceFile {
    pub rust_module: Option<&'static str>,
    pub linux_source: &'static str,
    pub required_markers: &'static [&'static str],
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CertsBuildRule {
    pub config: &'static str,
    pub objects: &'static [&'static str],
}

pub const CERTS_IMPLEMENTATIONS: &[CertsSourceFile] = &[
    CertsSourceFile {
        rust_module: Some("system_keyring"),
        linux_source: "vendor/linux/certs/system_keyring.c",
        required_markers: &[
            "static struct key *builtin_trusted_keys;",
            "restrict_link_by_builtin_trusted",
            "restrict_link_by_digsig_builtin",
            "restrict_link_by_builtin_and_secondary_trusted",
            "restrict_link_by_builtin_secondary_and_machine",
            "device_initcall(system_trusted_keyring_init);",
            "__init int load_module_cert(struct key *keyring)",
            "late_initcall(load_system_certificate_list);",
            "verify_pkcs7_message_sig",
            "EXPORT_SYMBOL_GPL(verify_pkcs7_signature);",
            "set_platform_trusted_keys",
        ],
    },
    CertsSourceFile {
        rust_module: Some("blacklist"),
        linux_source: "vendor/linux/certs/blacklist.c",
        required_markers: &[
            "static const char tbs_prefix[] = \"tbs\";",
            "static const char bin_prefix[] = \"bin\";",
            "blacklist_vet_description",
            "blacklist_key_instantiate",
            "mark_raw_hash_blacklisted",
            "is_hash_blacklisted",
            "is_binary_blacklisted",
            "add_key_to_revocation_list",
            "is_key_on_revocation_list",
            "device_initcall(blacklist_init);",
            "late_initcall(load_revocation_certificate_list);",
        ],
    },
    CertsSourceFile {
        rust_module: Some("blacklist_hashes"),
        linux_source: "vendor/linux/certs/blacklist_hashes.c",
        required_markers: &[
            "#include \"blacklist.h\"",
            "const char __initconst *const blacklist_hashes[]",
            "#include \"blacklist_hash_list\"",
        ],
    },
    CertsSourceFile {
        rust_module: Some("extract_cert"),
        linux_source: "vendor/linux/certs/extract-cert.c",
        required_markers: &[
            "Usage: extract-cert <source> <dest>",
            "KBUILD_VERBOSE",
            "KBUILD_SIGN_PIN",
            "OSSL_PROVIDER_try_load(NULL, \"pkcs11\", true)",
            "OSSL_STORE_open(cert_src, NULL, NULL, NULL, NULL)",
            "ENGINE_ctrl_cmd(e, \"LOAD_CERT_CTRL\"",
            "PEM_read_bio_X509",
            "i2d_X509_bio(wb, x509)",
        ],
    },
];

pub const CERTS_METADATA: &[CertsSourceFile] = &[
    CertsSourceFile {
        rust_module: None,
        linux_source: "vendor/linux/certs/.gitignore",
        required_markers: &[
            "/blacklist_hash_list",
            "/extract-cert",
            "/x509_certificate_list",
            "/x509_revocation_list",
        ],
    },
    CertsSourceFile {
        rust_module: None,
        linux_source: "vendor/linux/certs/revocation_certificates.S",
        required_markers: &[
            "__INITRODATA",
            ".globl revocation_certificate_list",
            ".incbin \"certs/x509_revocation_list\"",
            ".globl revocation_certificate_list_size",
        ],
    },
    CertsSourceFile {
        rust_module: None,
        linux_source: "vendor/linux/certs/Makefile",
        required_markers: &[
            "obj-$(CONFIG_SYSTEM_TRUSTED_KEYRING) += system_keyring.o system_certificates.o",
            "obj-$(CONFIG_SYSTEM_BLACKLIST_KEYRING) += blacklist.o blacklist_hashes.o",
            "obj-$(CONFIG_SYSTEM_REVOCATION_LIST) += revocation_certificates.o",
            "$(obj)/blacklist_hash_list: $(CONFIG_SYSTEM_BLACKLIST_HASH_LIST) FORCE",
            "$(obj)/x509_certificate_list: $(CONFIG_SYSTEM_TRUSTED_KEYS) $(obj)/extract-cert FORCE",
            "$(obj)/signing_key.pem: $(obj)/x509.genkey FORCE",
            "$(obj)/x509_revocation_list: $(CONFIG_SYSTEM_REVOCATION_KEYS) $(obj)/extract-cert FORCE",
            "hostprogs := extract-cert",
        ],
    },
    CertsSourceFile {
        rust_module: None,
        linux_source: "vendor/linux/certs/default_x509.genkey",
        required_markers: &[
            "default_bits = 4096",
            "CN = Build time autogenerated kernel key",
            "basicConstraints=critical,CA:FALSE",
            "keyUsage=digitalSignature",
            "subjectKeyIdentifier=hash",
            "authorityKeyIdentifier=keyid",
        ],
    },
    CertsSourceFile {
        rust_module: None,
        linux_source: "vendor/linux/certs/blacklist.h",
        required_markers: &[
            "#include <linux/kernel.h>",
            "#include <linux/errno.h>",
            "#include <crypto/pkcs7.h>",
            "extern const char __initconst *const blacklist_hashes[];",
        ],
    },
    CertsSourceFile {
        rust_module: None,
        linux_source: "vendor/linux/certs/check-blacklist-hashes.awk",
        required_markers: &[
            "RS = \",\"",
            "Not a string (item ",
            "Unknown prefix (item ",
            "Not a lowercase hexadecimal string (item ",
            "Hash string too long (item ",
            "Not an even number of hexadecimal characters (item ",
        ],
    },
    CertsSourceFile {
        rust_module: None,
        linux_source: "vendor/linux/certs/system_certificates.S",
        required_markers: &[
            "__INITRODATA",
            ".globl system_certificate_list",
            ".incbin \"certs/signing_key.x509\"",
            ".incbin \"certs/x509_certificate_list\"",
            ".globl system_extra_cert",
            ".globl system_certificate_list_size",
            ".globl module_cert_size",
        ],
    },
    CertsSourceFile {
        rust_module: None,
        linux_source: "vendor/linux/certs/Kconfig",
        required_markers: &[
            "menu \"Certificates for signature checking\"",
            "config MODULE_SIG_KEY",
            "config MODULE_SIG_KEY_TYPE_RSA",
            "config MODULE_SIG_KEY_TYPE_ECDSA",
            "config MODULE_SIG_KEY_TYPE_MLDSA_44",
            "config SYSTEM_TRUSTED_KEYRING",
            "config SYSTEM_TRUSTED_KEYS",
            "config SYSTEM_EXTRA_CERTIFICATE",
            "config SECONDARY_TRUSTED_KEYRING",
            "config SYSTEM_BLACKLIST_KEYRING",
            "config SYSTEM_BLACKLIST_HASH_LIST",
            "config SYSTEM_REVOCATION_LIST",
            "config SYSTEM_REVOCATION_KEYS",
            "config SYSTEM_BLACKLIST_AUTH_UPDATE",
            "config OPENSSL_SUPPORTS_ML_DSA",
        ],
    },
];

pub const CERTS_BUILD_RULES: &[CertsBuildRule] = &[
    CertsBuildRule {
        config: "CONFIG_SYSTEM_TRUSTED_KEYRING",
        objects: &["system_keyring.o", "system_certificates.o"],
    },
    CertsBuildRule {
        config: "CONFIG_SYSTEM_BLACKLIST_KEYRING",
        objects: &["blacklist.o", "blacklist_hashes.o"],
    },
    CertsBuildRule {
        config: "CONFIG_SYSTEM_REVOCATION_LIST",
        objects: &["revocation_certificates.o"],
    },
];

pub const CERTS_KCONFIG_SYMBOLS: &[&str] = &[
    "MODULE_SIG_KEY",
    "MODULE_SIG_KEY_TYPE_RSA",
    "MODULE_SIG_KEY_TYPE_ECDSA",
    "MODULE_SIG_KEY_TYPE_MLDSA_44",
    "MODULE_SIG_KEY_TYPE_MLDSA_65",
    "MODULE_SIG_KEY_TYPE_MLDSA_87",
    "SYSTEM_TRUSTED_KEYRING",
    "SYSTEM_TRUSTED_KEYS",
    "SYSTEM_EXTRA_CERTIFICATE",
    "SYSTEM_EXTRA_CERTIFICATE_SIZE",
    "SECONDARY_TRUSTED_KEYRING",
    "SECONDARY_TRUSTED_KEYRING_SIGNED_BY_BUILTIN",
    "SYSTEM_BLACKLIST_KEYRING",
    "SYSTEM_BLACKLIST_HASH_LIST",
    "SYSTEM_REVOCATION_LIST",
    "SYSTEM_REVOCATION_KEYS",
    "SYSTEM_BLACKLIST_AUTH_UPDATE",
    "OPENSSL_SUPPORTS_ML_DSA",
];

#[cfg(test)]
mod tests {
    use super::*;

    fn child_source(module: &str) -> &'static str {
        match module {
            "blacklist" => include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/src/certs/blacklist.rs"
            )),
            "blacklist_hashes" => include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/src/certs/blacklist_hashes.rs"
            )),
            "extract_cert" => include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/src/certs/extract_cert.rs"
            )),
            "system_keyring" => include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/src/certs/system_keyring.rs"
            )),
            _ => panic!("unknown certs module {module}"),
        }
    }

    fn linux_source(path: &str) -> &'static str {
        match path {
            "vendor/linux/certs/.gitignore" => include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/vendor/linux/certs/.gitignore"
            )),
            "vendor/linux/certs/revocation_certificates.S" => include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/vendor/linux/certs/revocation_certificates.S"
            )),
            "vendor/linux/certs/Makefile" => include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/vendor/linux/certs/Makefile"
            )),
            "vendor/linux/certs/default_x509.genkey" => include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/vendor/linux/certs/default_x509.genkey"
            )),
            "vendor/linux/certs/blacklist_hashes.c" => include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/vendor/linux/certs/blacklist_hashes.c"
            )),
            "vendor/linux/certs/blacklist.c" => include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/vendor/linux/certs/blacklist.c"
            )),
            "vendor/linux/certs/system_keyring.c" => include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/vendor/linux/certs/system_keyring.c"
            )),
            "vendor/linux/certs/blacklist.h" => include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/vendor/linux/certs/blacklist.h"
            )),
            "vendor/linux/certs/check-blacklist-hashes.awk" => include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/vendor/linux/certs/check-blacklist-hashes.awk"
            )),
            "vendor/linux/certs/extract-cert.c" => include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/vendor/linux/certs/extract-cert.c"
            )),
            "vendor/linux/certs/system_certificates.S" => include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/vendor/linux/certs/system_certificates.S"
            )),
            "vendor/linux/certs/Kconfig" => include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/vendor/linux/certs/Kconfig"
            )),
            _ => panic!("unknown certs source {path}"),
        }
    }

    #[test]
    fn implementation_inventory_matches_linux_sources_and_children() {
        assert_eq!(CERTS_IMPLEMENTATIONS.len(), 4);
        for entry in CERTS_IMPLEMENTATIONS {
            let module = entry.rust_module.expect("implementation module");
            let rust = child_source(module);
            let source = linux_source(entry.linux_source);

            assert!(rust.contains("//! linux-parity: complete"));
            assert!(
                rust.contains(&alloc::format!("//! linux-source: {}", entry.linux_source)),
                "{module} missing linux-source tag {}",
                entry.linux_source
            );
            for marker in entry.required_markers {
                assert!(
                    source.contains(marker),
                    "{} missing {}",
                    entry.linux_source,
                    marker
                );
            }
        }
    }

    #[test]
    fn metadata_inventory_matches_each_linux_certs_artifact() {
        assert_eq!(CERTS_METADATA.len(), 8);
        for entry in CERTS_METADATA {
            let source = linux_source(entry.linux_source);
            assert_eq!(entry.rust_module, None);
            for marker in entry.required_markers {
                assert!(
                    source.contains(marker),
                    "{} missing {}",
                    entry.linux_source,
                    marker
                );
            }
        }
    }

    #[test]
    fn makefile_build_rules_match_linux_objects() {
        let makefile = linux_source("vendor/linux/certs/Makefile");

        assert_eq!(CERTS_BUILD_RULES.len(), 3);
        for rule in CERTS_BUILD_RULES {
            let needle = alloc::format!("obj-$({})", rule.config);
            assert!(makefile.contains(&needle), "missing build rule {needle}");
            for object in rule.objects {
                assert!(makefile.contains(object), "missing object {object}");
            }
        }
    }

    #[test]
    fn kconfig_symbol_inventory_matches_linux_certs_menu() {
        let kconfig = linux_source("vendor/linux/certs/Kconfig");

        assert_eq!(CERTS_KCONFIG_SYMBOLS.len(), 18);
        for symbol in CERTS_KCONFIG_SYMBOLS {
            let needle = alloc::format!("config {symbol}");
            assert!(kconfig.contains(&needle), "missing Kconfig symbol {symbol}");
        }
    }
}
