//! linux-parity: complete
//! linux-source: vendor/linux/drivers/tty
//! test-origin: linux:vendor/linux/drivers/tty
//! Linux TTY layer (drivers/tty) source coverage.
//!
//! Linux source inventory for this subsystem. These references are source
//! truth for ABI glue, module staging, and parity audits; driver
//! implementations remain vendor-built Linux artifacts.
//!
//! Refs:
//! - `vendor/linux/drivers/tty/{amiserial,ehv_bytechan,goldfish,hvc/hvc_console,hvc/hvc_dcc,hvc/hvc_irq,hvc/hvc_iucv,hvc/hvc_opal,hvc/hvc_riscv_sbi,hvc/hvc_rtas,hvc/hvc_udbg,hvc/hvc_vio,hvc/hvc_xen,hvc/hvcs,hvc/hvsi,hvc/hvsi_lib,ipwireless/hardware,ipwireless/main,ipwireless/network,ipwireless/tty,mips_ejtag_fdc,moxa,mxser,n_gsm,n_hdlc,n_null,nozomi,pty,rpmsg_tty,serdev/core,serdev/serdev-ttyport,serial/21285,serial/8250/8250_accent,serial/8250/8250_acorn,serial/8250/8250_aspeed_vuart,serial/8250/8250_bcm2835aux,serial/8250/8250_bcm7271,serial/8250/8250_boca,serial/8250/8250_ce4100,serial/8250/8250_dfl,serial/8250/8250_dma,serial/8250/8250_dw,serial/8250/8250_dwlib,serial/8250/8250_early,serial/8250/8250_em,serial/8250/8250_exar,serial/8250/8250_exar_st16c554,serial/8250/8250_fintek,serial/8250/8250_fourport,serial/8250/8250_fsl,serial/8250/8250_hp300,serial/8250/8250_hub6,serial/8250/8250_ingenic,serial/8250/8250_ioc3,serial/8250/8250_keba,serial/8250/8250_loongson,serial/8250/8250_lpc18xx,serial/8250/8250_lpss,serial/8250/8250_men_mcb,serial/8250/8250_mid,serial/8250/8250_mtk,serial/8250/8250_ni,serial/8250/8250_of,serial/8250/8250_omap,serial/8250/8250_parisc,serial/8250/8250_pci,serial/8250/8250_pci1xxxx,serial/8250/8250_pcilib,serial/8250/8250_pericom,serial/8250/8250_platform,serial/8250/8250_pnp,serial/8250/8250_port,serial/8250/8250_pxa,serial/8250/8250_rsa,serial/8250/8250_rt288x,serial/8250/8250_tegra,serial/8250/8250_uniphier,serial/8250/serial_cs,serial/altera_jtaguart,serial/altera_uart,serial/amba-pl010,serial/amba-pl011,serial/apbuart,serial/ar933x_uart,serial/arc_uart,serial/atmel_serial,serial/bcm63xx_uart,serial/clps711x,serial/cpm_uart,serial/digicolor-usart,serial/dz,serial/earlycon,serial/earlycon-riscv-sbi,serial/earlycon-semihost,serial/esp32_acm,serial/esp32_uart,serial/fsl_linflexuart,serial/fsl_lpuart,serial/icom,serial/imx,serial/imx_earlycon,serial/ip22zilog,serial/jsm/jsm_cls,serial/jsm/jsm_driver,serial/jsm/jsm_neo,serial/jsm/jsm_tty,serial/kgdboc,serial/lantiq,serial/liteuart,serial/lpc32xx_hs,serial/ma35d1_serial,serial/max3100,serial/max310x,serial/mcf,serial/men_z135_uart,serial/meson_uart,serial/milbeaut_usio,serial/mpc52xx_uart,serial/mps2-uart,serial/msm_serial,serial/mux,serial/mvebu-uart,serial/mxs-auart,serial/omap-serial,serial/owl-uart,serial/pch_uart,serial/pic32_uart,serial/pmac_zilog,serial/pxa,serial/qcom_geni_serial,serial/rda-uart,serial/rp2,serial/rsci,serial/sa1100,serial/samsung_tty,serial/sb1250-duart,serial/sc16is7xx,serial/sc16is7xx_i2c,serial/sc16is7xx_spi,serial/sccnxp,serial/serial-tegra,serial/serial_base_bus,serial/serial_ctrl,serial/serial_mctrl_gpio,serial/serial_port,serial/serial_txx9,serial/sh-sci,serial/sifive,serial/sprd_serial,serial/st-asc,serial/stm32-usart,serial/suncore,serial/sunhv,serial/sunplus-uart,serial/sunsab,serial/sunsu,serial/sunzilog,serial/tegra-tcu,serial/tegra-utc,serial/timbuart,serial/uartlite,serial/ucc_uart,serial/vt8500_serial,serial/xilinx_uartps,serial/zs,synclink_gt,sysrq,tty_audit,tty_baudrate,tty_buffer,tty_ioctl,tty_ldisc,tty_ldsem,tty_mutex,tty_port,ttynull,vcc,vt/conmakehash,vt/consolemap,vt/keyboard,vt/selection,vt/ucs,vt/vc_screen,vt/vt,vt/vt_ioctl}.c`

/// Number of Linux `.c` files catalogued for this subsystem.
pub const TTY_SOURCES_COUNT: usize = 185;

/// Catalogued upstream Linux source paths used as source truth.
pub const TTY_SOURCES: &[&str] = &[
    "vendor/linux/drivers/tty/amiserial.c",
    "vendor/linux/drivers/tty/ehv_bytechan.c",
    "vendor/linux/drivers/tty/goldfish.c",
    "vendor/linux/drivers/tty/hvc/hvc_console.c",
    "vendor/linux/drivers/tty/hvc/hvc_dcc.c",
    "vendor/linux/drivers/tty/hvc/hvc_irq.c",
    "vendor/linux/drivers/tty/hvc/hvc_iucv.c",
    "vendor/linux/drivers/tty/hvc/hvc_opal.c",
    "vendor/linux/drivers/tty/hvc/hvc_riscv_sbi.c",
    "vendor/linux/drivers/tty/hvc/hvc_rtas.c",
    "vendor/linux/drivers/tty/hvc/hvc_udbg.c",
    "vendor/linux/drivers/tty/hvc/hvc_vio.c",
    "vendor/linux/drivers/tty/hvc/hvc_xen.c",
    "vendor/linux/drivers/tty/hvc/hvcs.c",
    "vendor/linux/drivers/tty/hvc/hvsi.c",
    "vendor/linux/drivers/tty/hvc/hvsi_lib.c",
    "vendor/linux/drivers/tty/ipwireless/hardware.c",
    "vendor/linux/drivers/tty/ipwireless/main.c",
    "vendor/linux/drivers/tty/ipwireless/network.c",
    "vendor/linux/drivers/tty/ipwireless/tty.c",
    "vendor/linux/drivers/tty/mips_ejtag_fdc.c",
    "vendor/linux/drivers/tty/moxa.c",
    "vendor/linux/drivers/tty/mxser.c",
    "vendor/linux/drivers/tty/n_gsm.c",
    "vendor/linux/drivers/tty/n_hdlc.c",
    "vendor/linux/drivers/tty/n_null.c",
    "vendor/linux/drivers/tty/nozomi.c",
    "vendor/linux/drivers/tty/pty.c",
    "vendor/linux/drivers/tty/rpmsg_tty.c",
    "vendor/linux/drivers/tty/serdev/core.c",
    "vendor/linux/drivers/tty/serdev/serdev-ttyport.c",
    "vendor/linux/drivers/tty/serial/21285.c",
    "vendor/linux/drivers/tty/serial/8250/8250_accent.c",
    "vendor/linux/drivers/tty/serial/8250/8250_acorn.c",
    "vendor/linux/drivers/tty/serial/8250/8250_aspeed_vuart.c",
    "vendor/linux/drivers/tty/serial/8250/8250_bcm2835aux.c",
    "vendor/linux/drivers/tty/serial/8250/8250_bcm7271.c",
    "vendor/linux/drivers/tty/serial/8250/8250_boca.c",
    "vendor/linux/drivers/tty/serial/8250/8250_ce4100.c",
    "vendor/linux/drivers/tty/serial/8250/8250_dfl.c",
    "vendor/linux/drivers/tty/serial/8250/8250_dma.c",
    "vendor/linux/drivers/tty/serial/8250/8250_dw.c",
    "vendor/linux/drivers/tty/serial/8250/8250_dwlib.c",
    "vendor/linux/drivers/tty/serial/8250/8250_early.c",
    "vendor/linux/drivers/tty/serial/8250/8250_em.c",
    "vendor/linux/drivers/tty/serial/8250/8250_exar.c",
    "vendor/linux/drivers/tty/serial/8250/8250_exar_st16c554.c",
    "vendor/linux/drivers/tty/serial/8250/8250_fintek.c",
    "vendor/linux/drivers/tty/serial/8250/8250_fourport.c",
    "vendor/linux/drivers/tty/serial/8250/8250_fsl.c",
    "vendor/linux/drivers/tty/serial/8250/8250_hp300.c",
    "vendor/linux/drivers/tty/serial/8250/8250_hub6.c",
    "vendor/linux/drivers/tty/serial/8250/8250_ingenic.c",
    "vendor/linux/drivers/tty/serial/8250/8250_ioc3.c",
    "vendor/linux/drivers/tty/serial/8250/8250_keba.c",
    "vendor/linux/drivers/tty/serial/8250/8250_loongson.c",
    "vendor/linux/drivers/tty/serial/8250/8250_lpc18xx.c",
    "vendor/linux/drivers/tty/serial/8250/8250_lpss.c",
    "vendor/linux/drivers/tty/serial/8250/8250_men_mcb.c",
    "vendor/linux/drivers/tty/serial/8250/8250_mid.c",
    "vendor/linux/drivers/tty/serial/8250/8250_mtk.c",
    "vendor/linux/drivers/tty/serial/8250/8250_ni.c",
    "vendor/linux/drivers/tty/serial/8250/8250_of.c",
    "vendor/linux/drivers/tty/serial/8250/8250_omap.c",
    "vendor/linux/drivers/tty/serial/8250/8250_parisc.c",
    "vendor/linux/drivers/tty/serial/8250/8250_pci.c",
    "vendor/linux/drivers/tty/serial/8250/8250_pci1xxxx.c",
    "vendor/linux/drivers/tty/serial/8250/8250_pcilib.c",
    "vendor/linux/drivers/tty/serial/8250/8250_pericom.c",
    "vendor/linux/drivers/tty/serial/8250/8250_platform.c",
    "vendor/linux/drivers/tty/serial/8250/8250_pnp.c",
    "vendor/linux/drivers/tty/serial/8250/8250_port.c",
    "vendor/linux/drivers/tty/serial/8250/8250_pxa.c",
    "vendor/linux/drivers/tty/serial/8250/8250_rsa.c",
    "vendor/linux/drivers/tty/serial/8250/8250_rt288x.c",
    "vendor/linux/drivers/tty/serial/8250/8250_tegra.c",
    "vendor/linux/drivers/tty/serial/8250/8250_uniphier.c",
    "vendor/linux/drivers/tty/serial/8250/serial_cs.c",
    "vendor/linux/drivers/tty/serial/altera_jtaguart.c",
    "vendor/linux/drivers/tty/serial/altera_uart.c",
    "vendor/linux/drivers/tty/serial/amba-pl010.c",
    "vendor/linux/drivers/tty/serial/amba-pl011.c",
    "vendor/linux/drivers/tty/serial/apbuart.c",
    "vendor/linux/drivers/tty/serial/ar933x_uart.c",
    "vendor/linux/drivers/tty/serial/arc_uart.c",
    "vendor/linux/drivers/tty/serial/atmel_serial.c",
    "vendor/linux/drivers/tty/serial/bcm63xx_uart.c",
    "vendor/linux/drivers/tty/serial/clps711x.c",
    "vendor/linux/drivers/tty/serial/cpm_uart.c",
    "vendor/linux/drivers/tty/serial/digicolor-usart.c",
    "vendor/linux/drivers/tty/serial/dz.c",
    "vendor/linux/drivers/tty/serial/earlycon.c",
    "vendor/linux/drivers/tty/serial/earlycon-riscv-sbi.c",
    "vendor/linux/drivers/tty/serial/earlycon-semihost.c",
    "vendor/linux/drivers/tty/serial/esp32_acm.c",
    "vendor/linux/drivers/tty/serial/esp32_uart.c",
    "vendor/linux/drivers/tty/serial/fsl_linflexuart.c",
    "vendor/linux/drivers/tty/serial/fsl_lpuart.c",
    "vendor/linux/drivers/tty/serial/icom.c",
    "vendor/linux/drivers/tty/serial/imx.c",
    "vendor/linux/drivers/tty/serial/imx_earlycon.c",
    "vendor/linux/drivers/tty/serial/ip22zilog.c",
    "vendor/linux/drivers/tty/serial/jsm/jsm_cls.c",
    "vendor/linux/drivers/tty/serial/jsm/jsm_driver.c",
    "vendor/linux/drivers/tty/serial/jsm/jsm_neo.c",
    "vendor/linux/drivers/tty/serial/jsm/jsm_tty.c",
    "vendor/linux/drivers/tty/serial/kgdboc.c",
    "vendor/linux/drivers/tty/serial/lantiq.c",
    "vendor/linux/drivers/tty/serial/liteuart.c",
    "vendor/linux/drivers/tty/serial/lpc32xx_hs.c",
    "vendor/linux/drivers/tty/serial/ma35d1_serial.c",
    "vendor/linux/drivers/tty/serial/max3100.c",
    "vendor/linux/drivers/tty/serial/max310x.c",
    "vendor/linux/drivers/tty/serial/mcf.c",
    "vendor/linux/drivers/tty/serial/men_z135_uart.c",
    "vendor/linux/drivers/tty/serial/meson_uart.c",
    "vendor/linux/drivers/tty/serial/milbeaut_usio.c",
    "vendor/linux/drivers/tty/serial/mpc52xx_uart.c",
    "vendor/linux/drivers/tty/serial/mps2-uart.c",
    "vendor/linux/drivers/tty/serial/msm_serial.c",
    "vendor/linux/drivers/tty/serial/mux.c",
    "vendor/linux/drivers/tty/serial/mvebu-uart.c",
    "vendor/linux/drivers/tty/serial/mxs-auart.c",
    "vendor/linux/drivers/tty/serial/omap-serial.c",
    "vendor/linux/drivers/tty/serial/owl-uart.c",
    "vendor/linux/drivers/tty/serial/pch_uart.c",
    "vendor/linux/drivers/tty/serial/pic32_uart.c",
    "vendor/linux/drivers/tty/serial/pmac_zilog.c",
    "vendor/linux/drivers/tty/serial/pxa.c",
    "vendor/linux/drivers/tty/serial/qcom_geni_serial.c",
    "vendor/linux/drivers/tty/serial/rda-uart.c",
    "vendor/linux/drivers/tty/serial/rp2.c",
    "vendor/linux/drivers/tty/serial/rsci.c",
    "vendor/linux/drivers/tty/serial/sa1100.c",
    "vendor/linux/drivers/tty/serial/samsung_tty.c",
    "vendor/linux/drivers/tty/serial/sb1250-duart.c",
    "vendor/linux/drivers/tty/serial/sc16is7xx.c",
    "vendor/linux/drivers/tty/serial/sc16is7xx_i2c.c",
    "vendor/linux/drivers/tty/serial/sc16is7xx_spi.c",
    "vendor/linux/drivers/tty/serial/sccnxp.c",
    "vendor/linux/drivers/tty/serial/serial-tegra.c",
    "vendor/linux/drivers/tty/serial/serial_base_bus.c",
    "vendor/linux/drivers/tty/serial/serial_ctrl.c",
    "vendor/linux/drivers/tty/serial/serial_mctrl_gpio.c",
    "vendor/linux/drivers/tty/serial/serial_port.c",
    "vendor/linux/drivers/tty/serial/serial_txx9.c",
    "vendor/linux/drivers/tty/serial/sh-sci.c",
    "vendor/linux/drivers/tty/serial/sifive.c",
    "vendor/linux/drivers/tty/serial/sprd_serial.c",
    "vendor/linux/drivers/tty/serial/st-asc.c",
    "vendor/linux/drivers/tty/serial/stm32-usart.c",
    "vendor/linux/drivers/tty/serial/suncore.c",
    "vendor/linux/drivers/tty/serial/sunhv.c",
    "vendor/linux/drivers/tty/serial/sunplus-uart.c",
    "vendor/linux/drivers/tty/serial/sunsab.c",
    "vendor/linux/drivers/tty/serial/sunsu.c",
    "vendor/linux/drivers/tty/serial/sunzilog.c",
    "vendor/linux/drivers/tty/serial/tegra-tcu.c",
    "vendor/linux/drivers/tty/serial/tegra-utc.c",
    "vendor/linux/drivers/tty/serial/timbuart.c",
    "vendor/linux/drivers/tty/serial/uartlite.c",
    "vendor/linux/drivers/tty/serial/ucc_uart.c",
    "vendor/linux/drivers/tty/serial/vt8500_serial.c",
    "vendor/linux/drivers/tty/serial/xilinx_uartps.c",
    "vendor/linux/drivers/tty/serial/zs.c",
    "vendor/linux/drivers/tty/synclink_gt.c",
    "vendor/linux/drivers/tty/sysrq.c",
    "vendor/linux/drivers/tty/tty_audit.c",
    "vendor/linux/drivers/tty/tty_baudrate.c",
    "vendor/linux/drivers/tty/tty_buffer.c",
    "vendor/linux/drivers/tty/tty_ioctl.c",
    "vendor/linux/drivers/tty/tty_ldisc.c",
    "vendor/linux/drivers/tty/tty_ldsem.c",
    "vendor/linux/drivers/tty/tty_mutex.c",
    "vendor/linux/drivers/tty/tty_port.c",
    "vendor/linux/drivers/tty/ttynull.c",
    "vendor/linux/drivers/tty/vcc.c",
    "vendor/linux/drivers/tty/vt/conmakehash.c",
    "vendor/linux/drivers/tty/vt/consolemap.c",
    "vendor/linux/drivers/tty/vt/keyboard.c",
    "vendor/linux/drivers/tty/vt/selection.c",
    "vendor/linux/drivers/tty/vt/ucs.c",
    "vendor/linux/drivers/tty/vt/vc_screen.c",
    "vendor/linux/drivers/tty/vt/vt.c",
    "vendor/linux/drivers/tty/vt/vt_ioctl.c",
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn count_matches_table() {
        assert_eq!(TTY_SOURCES.len(), TTY_SOURCES_COUNT);
    }

    #[test]
    fn all_paths_have_canonical_prefix() {
        for path in TTY_SOURCES {
            assert!(path.starts_with("vendor/linux/drivers/tty/"), "{path}");
            assert!(path.ends_with(".c"));
        }
    }
}
