// SPDX-License-Identifier: ((GPL-2.0 WITH Linux-syscall-note) OR BSD-3-Clause)
//! linux-source: include/uapi/linux/ethtool_netlink_generated.h
//! linux-revision: 425f94c2954b1fe80ebdbf9b29854e89750355df
//! architectures: common
//! rewrite-task: S016119

// Auto-generated UAPI definitions translated from Documentation/netlink/specs/ethtool.yaml.

pub const ETHTOOL_GENL_NAME: &[u8; 8] = b"ethtool\0";
pub const ETHTOOL_GENL_VERSION: i32 = 1;
pub const ETHTOOL_UDP_TUNNEL_TYPE_VXLAN: i32 = 0;
pub const ETHTOOL_UDP_TUNNEL_TYPE_GENEVE: i32 = ETHTOOL_UDP_TUNNEL_TYPE_VXLAN + 1;
pub const ETHTOOL_UDP_TUNNEL_TYPE_VXLAN_GPE: i32 = ETHTOOL_UDP_TUNNEL_TYPE_GENEVE + 1;
pub const __ETHTOOL_UDP_TUNNEL_TYPE_CNT: i32 = ETHTOOL_UDP_TUNNEL_TYPE_VXLAN_GPE + 1;
pub const ETHTOOL_UDP_TUNNEL_TYPE_MAX: i32 = (__ETHTOOL_UDP_TUNNEL_TYPE_CNT - 1);

pub type ethtool_header_flags = i32;
pub const ETHTOOL_FLAG_COMPACT_BITSETS: ethtool_header_flags = 1;
pub const ETHTOOL_FLAG_OMIT_REPLY: ethtool_header_flags = 2;
pub const ETHTOOL_FLAG_STATS: ethtool_header_flags = 4;

pub type ethtool_tcp_data_split = i32;
pub const ETHTOOL_TCP_DATA_SPLIT_UNKNOWN: ethtool_tcp_data_split = 0;
pub const ETHTOOL_TCP_DATA_SPLIT_DISABLED: ethtool_tcp_data_split = ETHTOOL_TCP_DATA_SPLIT_UNKNOWN + 1;
pub const ETHTOOL_TCP_DATA_SPLIT_ENABLED: ethtool_tcp_data_split = ETHTOOL_TCP_DATA_SPLIT_DISABLED + 1;

pub type hwtstamp_source = i32;
pub const HWTSTAMP_SOURCE_NETDEV: hwtstamp_source = 1;
pub const HWTSTAMP_SOURCE_PHYLIB: hwtstamp_source = HWTSTAMP_SOURCE_NETDEV + 1;

pub type ethtool_pse_event = i32;
pub const ETHTOOL_PSE_EVENT_OVER_CURRENT: ethtool_pse_event = 1;
pub const ETHTOOL_PSE_EVENT_OVER_TEMP: ethtool_pse_event = 2;
pub const ETHTOOL_C33_PSE_EVENT_DETECTION: ethtool_pse_event = 4;
pub const ETHTOOL_C33_PSE_EVENT_CLASSIFICATION: ethtool_pse_event = 8;
pub const ETHTOOL_C33_PSE_EVENT_DISCONNECTION: ethtool_pse_event = 16;
pub const ETHTOOL_PSE_EVENT_OVER_BUDGET: ethtool_pse_event = 32;
pub const ETHTOOL_PSE_EVENT_SW_PW_CONTROL_ERROR: ethtool_pse_event = 64;

pub const ETHTOOL_A_HEADER_UNSPEC: i32 = 0;
pub const ETHTOOL_A_HEADER_DEV_INDEX: i32 = ETHTOOL_A_HEADER_UNSPEC + 1;
pub const ETHTOOL_A_HEADER_DEV_NAME: i32 = ETHTOOL_A_HEADER_DEV_INDEX + 1;
pub const ETHTOOL_A_HEADER_FLAGS: i32 = ETHTOOL_A_HEADER_DEV_NAME + 1;
pub const ETHTOOL_A_HEADER_PHY_INDEX: i32 = ETHTOOL_A_HEADER_FLAGS + 1;
pub const __ETHTOOL_A_HEADER_CNT: i32 = ETHTOOL_A_HEADER_PHY_INDEX + 1;
pub const ETHTOOL_A_HEADER_MAX: i32 = (__ETHTOOL_A_HEADER_CNT - 1);

pub const ETHTOOL_A_BITSET_BIT_UNSPEC: i32 = 0;
pub const ETHTOOL_A_BITSET_BIT_INDEX: i32 = ETHTOOL_A_BITSET_BIT_UNSPEC + 1;
pub const ETHTOOL_A_BITSET_BIT_NAME: i32 = ETHTOOL_A_BITSET_BIT_INDEX + 1;
pub const ETHTOOL_A_BITSET_BIT_VALUE: i32 = ETHTOOL_A_BITSET_BIT_NAME + 1;
pub const __ETHTOOL_A_BITSET_BIT_CNT: i32 = ETHTOOL_A_BITSET_BIT_VALUE + 1;
pub const ETHTOOL_A_BITSET_BIT_MAX: i32 = (__ETHTOOL_A_BITSET_BIT_CNT - 1);

pub const ETHTOOL_A_BITSET_BITS_UNSPEC: i32 = 0;
pub const ETHTOOL_A_BITSET_BITS_BIT: i32 = ETHTOOL_A_BITSET_BITS_UNSPEC + 1;
pub const __ETHTOOL_A_BITSET_BITS_CNT: i32 = ETHTOOL_A_BITSET_BITS_BIT + 1;
pub const ETHTOOL_A_BITSET_BITS_MAX: i32 = (__ETHTOOL_A_BITSET_BITS_CNT - 1);

pub const ETHTOOL_A_BITSET_UNSPEC: i32 = 0;
pub const ETHTOOL_A_BITSET_NOMASK: i32 = ETHTOOL_A_BITSET_UNSPEC + 1;
pub const ETHTOOL_A_BITSET_SIZE: i32 = ETHTOOL_A_BITSET_NOMASK + 1;
pub const ETHTOOL_A_BITSET_BITS: i32 = ETHTOOL_A_BITSET_SIZE + 1;
pub const ETHTOOL_A_BITSET_VALUE: i32 = ETHTOOL_A_BITSET_BITS + 1;
pub const ETHTOOL_A_BITSET_MASK: i32 = ETHTOOL_A_BITSET_VALUE + 1;
pub const __ETHTOOL_A_BITSET_CNT: i32 = ETHTOOL_A_BITSET_MASK + 1;
pub const ETHTOOL_A_BITSET_MAX: i32 = (__ETHTOOL_A_BITSET_CNT - 1);

pub const ETHTOOL_A_STRING_UNSPEC: i32 = 0;
pub const ETHTOOL_A_STRING_INDEX: i32 = ETHTOOL_A_STRING_UNSPEC + 1;
pub const ETHTOOL_A_STRING_VALUE: i32 = ETHTOOL_A_STRING_INDEX + 1;
pub const __ETHTOOL_A_STRING_CNT: i32 = ETHTOOL_A_STRING_VALUE + 1;
pub const ETHTOOL_A_STRING_MAX: i32 = (__ETHTOOL_A_STRING_CNT - 1);

pub const ETHTOOL_A_STRINGS_UNSPEC: i32 = 0;
pub const ETHTOOL_A_STRINGS_STRING: i32 = ETHTOOL_A_STRINGS_UNSPEC + 1;
pub const __ETHTOOL_A_STRINGS_CNT: i32 = ETHTOOL_A_STRINGS_STRING + 1;
pub const ETHTOOL_A_STRINGS_MAX: i32 = (__ETHTOOL_A_STRINGS_CNT - 1);

pub const ETHTOOL_A_STRINGSET_UNSPEC: i32 = 0;
pub const ETHTOOL_A_STRINGSET_ID: i32 = ETHTOOL_A_STRINGSET_UNSPEC + 1;
pub const ETHTOOL_A_STRINGSET_COUNT: i32 = ETHTOOL_A_STRINGSET_ID + 1;
pub const ETHTOOL_A_STRINGSET_STRINGS: i32 = ETHTOOL_A_STRINGSET_COUNT + 1;
pub const __ETHTOOL_A_STRINGSET_CNT: i32 = ETHTOOL_A_STRINGSET_STRINGS + 1;
pub const ETHTOOL_A_STRINGSET_MAX: i32 = (__ETHTOOL_A_STRINGSET_CNT - 1);

pub const ETHTOOL_A_STRINGSETS_UNSPEC: i32 = 0;
pub const ETHTOOL_A_STRINGSETS_STRINGSET: i32 = ETHTOOL_A_STRINGSETS_UNSPEC + 1;
pub const __ETHTOOL_A_STRINGSETS_CNT: i32 = ETHTOOL_A_STRINGSETS_STRINGSET + 1;
pub const ETHTOOL_A_STRINGSETS_MAX: i32 = (__ETHTOOL_A_STRINGSETS_CNT - 1);

pub const ETHTOOL_A_STRSET_UNSPEC: i32 = 0;
pub const ETHTOOL_A_STRSET_HEADER: i32 = ETHTOOL_A_STRSET_UNSPEC + 1;
pub const ETHTOOL_A_STRSET_STRINGSETS: i32 = ETHTOOL_A_STRSET_HEADER + 1;
pub const ETHTOOL_A_STRSET_COUNTS_ONLY: i32 = ETHTOOL_A_STRSET_STRINGSETS + 1;
pub const __ETHTOOL_A_STRSET_CNT: i32 = ETHTOOL_A_STRSET_COUNTS_ONLY + 1;
pub const ETHTOOL_A_STRSET_MAX: i32 = (__ETHTOOL_A_STRSET_CNT - 1);

pub const ETHTOOL_A_PRIVFLAGS_UNSPEC: i32 = 0;
pub const ETHTOOL_A_PRIVFLAGS_HEADER: i32 = ETHTOOL_A_PRIVFLAGS_UNSPEC + 1;
pub const ETHTOOL_A_PRIVFLAGS_FLAGS: i32 = ETHTOOL_A_PRIVFLAGS_HEADER + 1;
pub const __ETHTOOL_A_PRIVFLAGS_CNT: i32 = ETHTOOL_A_PRIVFLAGS_FLAGS + 1;
pub const ETHTOOL_A_PRIVFLAGS_MAX: i32 = (__ETHTOOL_A_PRIVFLAGS_CNT - 1);

pub const ETHTOOL_A_RINGS_UNSPEC: i32 = 0;
pub const ETHTOOL_A_RINGS_HEADER: i32 = ETHTOOL_A_RINGS_UNSPEC + 1;
pub const ETHTOOL_A_RINGS_RX_MAX: i32 = ETHTOOL_A_RINGS_HEADER + 1;
pub const ETHTOOL_A_RINGS_RX_MINI_MAX: i32 = ETHTOOL_A_RINGS_RX_MAX + 1;
pub const ETHTOOL_A_RINGS_RX_JUMBO_MAX: i32 = ETHTOOL_A_RINGS_RX_MINI_MAX + 1;
pub const ETHTOOL_A_RINGS_TX_MAX: i32 = ETHTOOL_A_RINGS_RX_JUMBO_MAX + 1;
pub const ETHTOOL_A_RINGS_RX: i32 = ETHTOOL_A_RINGS_TX_MAX + 1;
pub const ETHTOOL_A_RINGS_RX_MINI: i32 = ETHTOOL_A_RINGS_RX + 1;
pub const ETHTOOL_A_RINGS_RX_JUMBO: i32 = ETHTOOL_A_RINGS_RX_MINI + 1;
pub const ETHTOOL_A_RINGS_TX: i32 = ETHTOOL_A_RINGS_RX_JUMBO + 1;
pub const ETHTOOL_A_RINGS_RX_BUF_LEN: i32 = ETHTOOL_A_RINGS_TX + 1;
pub const ETHTOOL_A_RINGS_TCP_DATA_SPLIT: i32 = ETHTOOL_A_RINGS_RX_BUF_LEN + 1;
pub const ETHTOOL_A_RINGS_CQE_SIZE: i32 = ETHTOOL_A_RINGS_TCP_DATA_SPLIT + 1;
pub const ETHTOOL_A_RINGS_TX_PUSH: i32 = ETHTOOL_A_RINGS_CQE_SIZE + 1;
pub const ETHTOOL_A_RINGS_RX_PUSH: i32 = ETHTOOL_A_RINGS_TX_PUSH + 1;
pub const ETHTOOL_A_RINGS_TX_PUSH_BUF_LEN: i32 = ETHTOOL_A_RINGS_RX_PUSH + 1;
pub const ETHTOOL_A_RINGS_TX_PUSH_BUF_LEN_MAX: i32 = ETHTOOL_A_RINGS_TX_PUSH_BUF_LEN + 1;
pub const ETHTOOL_A_RINGS_HDS_THRESH: i32 = ETHTOOL_A_RINGS_TX_PUSH_BUF_LEN_MAX + 1;
pub const ETHTOOL_A_RINGS_HDS_THRESH_MAX: i32 = ETHTOOL_A_RINGS_HDS_THRESH + 1;
pub const __ETHTOOL_A_RINGS_CNT: i32 = ETHTOOL_A_RINGS_HDS_THRESH_MAX + 1;
pub const ETHTOOL_A_RINGS_MAX: i32 = (__ETHTOOL_A_RINGS_CNT - 1);

pub const ETHTOOL_A_MM_STAT_UNSPEC: i32 = 0;
pub const ETHTOOL_A_MM_STAT_PAD: i32 = ETHTOOL_A_MM_STAT_UNSPEC + 1;
pub const ETHTOOL_A_MM_STAT_REASSEMBLY_ERRORS: i32 = ETHTOOL_A_MM_STAT_PAD + 1;
pub const ETHTOOL_A_MM_STAT_SMD_ERRORS: i32 = ETHTOOL_A_MM_STAT_REASSEMBLY_ERRORS + 1;
pub const ETHTOOL_A_MM_STAT_REASSEMBLY_OK: i32 = ETHTOOL_A_MM_STAT_SMD_ERRORS + 1;
pub const ETHTOOL_A_MM_STAT_RX_FRAG_COUNT: i32 = ETHTOOL_A_MM_STAT_REASSEMBLY_OK + 1;
pub const ETHTOOL_A_MM_STAT_TX_FRAG_COUNT: i32 = ETHTOOL_A_MM_STAT_RX_FRAG_COUNT + 1;
pub const ETHTOOL_A_MM_STAT_HOLD_COUNT: i32 = ETHTOOL_A_MM_STAT_TX_FRAG_COUNT + 1;
pub const __ETHTOOL_A_MM_STAT_CNT: i32 = ETHTOOL_A_MM_STAT_HOLD_COUNT + 1;
pub const ETHTOOL_A_MM_STAT_MAX: i32 = (__ETHTOOL_A_MM_STAT_CNT - 1);

pub const ETHTOOL_A_MM_UNSPEC: i32 = 0;
pub const ETHTOOL_A_MM_HEADER: i32 = ETHTOOL_A_MM_UNSPEC + 1;
pub const ETHTOOL_A_MM_PMAC_ENABLED: i32 = ETHTOOL_A_MM_HEADER + 1;
pub const ETHTOOL_A_MM_TX_ENABLED: i32 = ETHTOOL_A_MM_PMAC_ENABLED + 1;
pub const ETHTOOL_A_MM_TX_ACTIVE: i32 = ETHTOOL_A_MM_TX_ENABLED + 1;
pub const ETHTOOL_A_MM_TX_MIN_FRAG_SIZE: i32 = ETHTOOL_A_MM_TX_ACTIVE + 1;
pub const ETHTOOL_A_MM_RX_MIN_FRAG_SIZE: i32 = ETHTOOL_A_MM_TX_MIN_FRAG_SIZE + 1;
pub const ETHTOOL_A_MM_VERIFY_ENABLED: i32 = ETHTOOL_A_MM_RX_MIN_FRAG_SIZE + 1;
pub const ETHTOOL_A_MM_VERIFY_STATUS: i32 = ETHTOOL_A_MM_VERIFY_ENABLED + 1;
pub const ETHTOOL_A_MM_VERIFY_TIME: i32 = ETHTOOL_A_MM_VERIFY_STATUS + 1;
pub const ETHTOOL_A_MM_MAX_VERIFY_TIME: i32 = ETHTOOL_A_MM_VERIFY_TIME + 1;
pub const ETHTOOL_A_MM_STATS: i32 = ETHTOOL_A_MM_MAX_VERIFY_TIME + 1;
pub const __ETHTOOL_A_MM_CNT: i32 = ETHTOOL_A_MM_STATS + 1;
pub const ETHTOOL_A_MM_MAX: i32 = (__ETHTOOL_A_MM_CNT - 1);

pub const ETHTOOL_A_LINKINFO_UNSPEC: i32 = 0;
pub const ETHTOOL_A_LINKINFO_HEADER: i32 = ETHTOOL_A_LINKINFO_UNSPEC + 1;
pub const ETHTOOL_A_LINKINFO_PORT: i32 = ETHTOOL_A_LINKINFO_HEADER + 1;
pub const ETHTOOL_A_LINKINFO_PHYADDR: i32 = ETHTOOL_A_LINKINFO_PORT + 1;
pub const ETHTOOL_A_LINKINFO_TP_MDIX: i32 = ETHTOOL_A_LINKINFO_PHYADDR + 1;
pub const ETHTOOL_A_LINKINFO_TP_MDIX_CTRL: i32 = ETHTOOL_A_LINKINFO_TP_MDIX + 1;
pub const ETHTOOL_A_LINKINFO_TRANSCEIVER: i32 = ETHTOOL_A_LINKINFO_TP_MDIX_CTRL + 1;
pub const __ETHTOOL_A_LINKINFO_CNT: i32 = ETHTOOL_A_LINKINFO_TRANSCEIVER + 1;
pub const ETHTOOL_A_LINKINFO_MAX: i32 = (__ETHTOOL_A_LINKINFO_CNT - 1);

pub const ETHTOOL_A_LINKMODES_UNSPEC: i32 = 0;
pub const ETHTOOL_A_LINKMODES_HEADER: i32 = ETHTOOL_A_LINKMODES_UNSPEC + 1;
pub const ETHTOOL_A_LINKMODES_AUTONEG: i32 = ETHTOOL_A_LINKMODES_HEADER + 1;
pub const ETHTOOL_A_LINKMODES_OURS: i32 = ETHTOOL_A_LINKMODES_AUTONEG + 1;
pub const ETHTOOL_A_LINKMODES_PEER: i32 = ETHTOOL_A_LINKMODES_OURS + 1;
pub const ETHTOOL_A_LINKMODES_SPEED: i32 = ETHTOOL_A_LINKMODES_PEER + 1;
pub const ETHTOOL_A_LINKMODES_DUPLEX: i32 = ETHTOOL_A_LINKMODES_SPEED + 1;
pub const ETHTOOL_A_LINKMODES_MASTER_SLAVE_CFG: i32 = ETHTOOL_A_LINKMODES_DUPLEX + 1;
pub const ETHTOOL_A_LINKMODES_MASTER_SLAVE_STATE: i32 = ETHTOOL_A_LINKMODES_MASTER_SLAVE_CFG + 1;
pub const ETHTOOL_A_LINKMODES_LANES: i32 = ETHTOOL_A_LINKMODES_MASTER_SLAVE_STATE + 1;
pub const ETHTOOL_A_LINKMODES_RATE_MATCHING: i32 = ETHTOOL_A_LINKMODES_LANES + 1;
pub const __ETHTOOL_A_LINKMODES_CNT: i32 = ETHTOOL_A_LINKMODES_RATE_MATCHING + 1;
pub const ETHTOOL_A_LINKMODES_MAX: i32 = (__ETHTOOL_A_LINKMODES_CNT - 1);

pub const ETHTOOL_A_LINKSTATE_UNSPEC: i32 = 0;
pub const ETHTOOL_A_LINKSTATE_HEADER: i32 = ETHTOOL_A_LINKSTATE_UNSPEC + 1;
pub const ETHTOOL_A_LINKSTATE_LINK: i32 = ETHTOOL_A_LINKSTATE_HEADER + 1;
pub const ETHTOOL_A_LINKSTATE_SQI: i32 = ETHTOOL_A_LINKSTATE_LINK + 1;
pub const ETHTOOL_A_LINKSTATE_SQI_MAX: i32 = ETHTOOL_A_LINKSTATE_SQI + 1;
pub const ETHTOOL_A_LINKSTATE_EXT_STATE: i32 = ETHTOOL_A_LINKSTATE_SQI_MAX + 1;
pub const ETHTOOL_A_LINKSTATE_EXT_SUBSTATE: i32 = ETHTOOL_A_LINKSTATE_EXT_STATE + 1;
pub const ETHTOOL_A_LINKSTATE_EXT_DOWN_CNT: i32 = ETHTOOL_A_LINKSTATE_EXT_SUBSTATE + 1;
pub const __ETHTOOL_A_LINKSTATE_CNT: i32 = ETHTOOL_A_LINKSTATE_EXT_DOWN_CNT + 1;
pub const ETHTOOL_A_LINKSTATE_MAX: i32 = (__ETHTOOL_A_LINKSTATE_CNT - 1);

pub const ETHTOOL_A_DEBUG_UNSPEC: i32 = 0;
pub const ETHTOOL_A_DEBUG_HEADER: i32 = ETHTOOL_A_DEBUG_UNSPEC + 1;
pub const ETHTOOL_A_DEBUG_MSGMASK: i32 = ETHTOOL_A_DEBUG_HEADER + 1;
pub const __ETHTOOL_A_DEBUG_CNT: i32 = ETHTOOL_A_DEBUG_MSGMASK + 1;
pub const ETHTOOL_A_DEBUG_MAX: i32 = (__ETHTOOL_A_DEBUG_CNT - 1);

pub const ETHTOOL_A_WOL_UNSPEC: i32 = 0;
pub const ETHTOOL_A_WOL_HEADER: i32 = ETHTOOL_A_WOL_UNSPEC + 1;
pub const ETHTOOL_A_WOL_MODES: i32 = ETHTOOL_A_WOL_HEADER + 1;
pub const ETHTOOL_A_WOL_SOPASS: i32 = ETHTOOL_A_WOL_MODES + 1;
pub const __ETHTOOL_A_WOL_CNT: i32 = ETHTOOL_A_WOL_SOPASS + 1;
pub const ETHTOOL_A_WOL_MAX: i32 = (__ETHTOOL_A_WOL_CNT - 1);

pub const ETHTOOL_A_FEATURES_UNSPEC: i32 = 0;
pub const ETHTOOL_A_FEATURES_HEADER: i32 = ETHTOOL_A_FEATURES_UNSPEC + 1;
pub const ETHTOOL_A_FEATURES_HW: i32 = ETHTOOL_A_FEATURES_HEADER + 1;
pub const ETHTOOL_A_FEATURES_WANTED: i32 = ETHTOOL_A_FEATURES_HW + 1;
pub const ETHTOOL_A_FEATURES_ACTIVE: i32 = ETHTOOL_A_FEATURES_WANTED + 1;
pub const ETHTOOL_A_FEATURES_NOCHANGE: i32 = ETHTOOL_A_FEATURES_ACTIVE + 1;
pub const __ETHTOOL_A_FEATURES_CNT: i32 = ETHTOOL_A_FEATURES_NOCHANGE + 1;
pub const ETHTOOL_A_FEATURES_MAX: i32 = (__ETHTOOL_A_FEATURES_CNT - 1);

pub const ETHTOOL_A_CHANNELS_UNSPEC: i32 = 0;
pub const ETHTOOL_A_CHANNELS_HEADER: i32 = ETHTOOL_A_CHANNELS_UNSPEC + 1;
pub const ETHTOOL_A_CHANNELS_RX_MAX: i32 = ETHTOOL_A_CHANNELS_HEADER + 1;
pub const ETHTOOL_A_CHANNELS_TX_MAX: i32 = ETHTOOL_A_CHANNELS_RX_MAX + 1;
pub const ETHTOOL_A_CHANNELS_OTHER_MAX: i32 = ETHTOOL_A_CHANNELS_TX_MAX + 1;
pub const ETHTOOL_A_CHANNELS_COMBINED_MAX: i32 = ETHTOOL_A_CHANNELS_OTHER_MAX + 1;
pub const ETHTOOL_A_CHANNELS_RX_COUNT: i32 = ETHTOOL_A_CHANNELS_COMBINED_MAX + 1;
pub const ETHTOOL_A_CHANNELS_TX_COUNT: i32 = ETHTOOL_A_CHANNELS_RX_COUNT + 1;
pub const ETHTOOL_A_CHANNELS_OTHER_COUNT: i32 = ETHTOOL_A_CHANNELS_TX_COUNT + 1;
pub const ETHTOOL_A_CHANNELS_COMBINED_COUNT: i32 = ETHTOOL_A_CHANNELS_OTHER_COUNT + 1;
pub const __ETHTOOL_A_CHANNELS_CNT: i32 = ETHTOOL_A_CHANNELS_COMBINED_COUNT + 1;
pub const ETHTOOL_A_CHANNELS_MAX: i32 = (__ETHTOOL_A_CHANNELS_CNT - 1);

pub const ETHTOOL_A_IRQ_MODERATION_UNSPEC: i32 = 0;
pub const ETHTOOL_A_IRQ_MODERATION_USEC: i32 = ETHTOOL_A_IRQ_MODERATION_UNSPEC + 1;
pub const ETHTOOL_A_IRQ_MODERATION_PKTS: i32 = ETHTOOL_A_IRQ_MODERATION_USEC + 1;
pub const ETHTOOL_A_IRQ_MODERATION_COMPS: i32 = ETHTOOL_A_IRQ_MODERATION_PKTS + 1;
pub const __ETHTOOL_A_IRQ_MODERATION_CNT: i32 = ETHTOOL_A_IRQ_MODERATION_COMPS + 1;
pub const ETHTOOL_A_IRQ_MODERATION_MAX: i32 = (__ETHTOOL_A_IRQ_MODERATION_CNT - 1);

pub const ETHTOOL_A_PROFILE_UNSPEC: i32 = 0;
pub const ETHTOOL_A_PROFILE_IRQ_MODERATION: i32 = ETHTOOL_A_PROFILE_UNSPEC + 1;
pub const __ETHTOOL_A_PROFILE_CNT: i32 = ETHTOOL_A_PROFILE_IRQ_MODERATION + 1;
pub const ETHTOOL_A_PROFILE_MAX: i32 = (__ETHTOOL_A_PROFILE_CNT - 1);

pub const ETHTOOL_A_COALESCE_UNSPEC: i32 = 0;
pub const ETHTOOL_A_COALESCE_HEADER: i32 = ETHTOOL_A_COALESCE_UNSPEC + 1;
pub const ETHTOOL_A_COALESCE_RX_USECS: i32 = ETHTOOL_A_COALESCE_HEADER + 1;
pub const ETHTOOL_A_COALESCE_RX_MAX_FRAMES: i32 = ETHTOOL_A_COALESCE_RX_USECS + 1;
pub const ETHTOOL_A_COALESCE_RX_USECS_IRQ: i32 = ETHTOOL_A_COALESCE_RX_MAX_FRAMES + 1;
pub const ETHTOOL_A_COALESCE_RX_MAX_FRAMES_IRQ: i32 = ETHTOOL_A_COALESCE_RX_USECS_IRQ + 1;
pub const ETHTOOL_A_COALESCE_TX_USECS: i32 = ETHTOOL_A_COALESCE_RX_MAX_FRAMES_IRQ + 1;
pub const ETHTOOL_A_COALESCE_TX_MAX_FRAMES: i32 = ETHTOOL_A_COALESCE_TX_USECS + 1;
pub const ETHTOOL_A_COALESCE_TX_USECS_IRQ: i32 = ETHTOOL_A_COALESCE_TX_MAX_FRAMES + 1;
pub const ETHTOOL_A_COALESCE_TX_MAX_FRAMES_IRQ: i32 = ETHTOOL_A_COALESCE_TX_USECS_IRQ + 1;
pub const ETHTOOL_A_COALESCE_STATS_BLOCK_USECS: i32 = ETHTOOL_A_COALESCE_TX_MAX_FRAMES_IRQ + 1;
pub const ETHTOOL_A_COALESCE_USE_ADAPTIVE_RX: i32 = ETHTOOL_A_COALESCE_STATS_BLOCK_USECS + 1;
pub const ETHTOOL_A_COALESCE_USE_ADAPTIVE_TX: i32 = ETHTOOL_A_COALESCE_USE_ADAPTIVE_RX + 1;
pub const ETHTOOL_A_COALESCE_PKT_RATE_LOW: i32 = ETHTOOL_A_COALESCE_USE_ADAPTIVE_TX + 1;
pub const ETHTOOL_A_COALESCE_RX_USECS_LOW: i32 = ETHTOOL_A_COALESCE_PKT_RATE_LOW + 1;
pub const ETHTOOL_A_COALESCE_RX_MAX_FRAMES_LOW: i32 = ETHTOOL_A_COALESCE_RX_USECS_LOW + 1;
pub const ETHTOOL_A_COALESCE_TX_USECS_LOW: i32 = ETHTOOL_A_COALESCE_RX_MAX_FRAMES_LOW + 1;
pub const ETHTOOL_A_COALESCE_TX_MAX_FRAMES_LOW: i32 = ETHTOOL_A_COALESCE_TX_USECS_LOW + 1;
pub const ETHTOOL_A_COALESCE_PKT_RATE_HIGH: i32 = ETHTOOL_A_COALESCE_TX_MAX_FRAMES_LOW + 1;
pub const ETHTOOL_A_COALESCE_RX_USECS_HIGH: i32 = ETHTOOL_A_COALESCE_PKT_RATE_HIGH + 1;
pub const ETHTOOL_A_COALESCE_RX_MAX_FRAMES_HIGH: i32 = ETHTOOL_A_COALESCE_RX_USECS_HIGH + 1;
pub const ETHTOOL_A_COALESCE_TX_USECS_HIGH: i32 = ETHTOOL_A_COALESCE_RX_MAX_FRAMES_HIGH + 1;
pub const ETHTOOL_A_COALESCE_TX_MAX_FRAMES_HIGH: i32 = ETHTOOL_A_COALESCE_TX_USECS_HIGH + 1;
pub const ETHTOOL_A_COALESCE_RATE_SAMPLE_INTERVAL: i32 = ETHTOOL_A_COALESCE_TX_MAX_FRAMES_HIGH + 1;
pub const ETHTOOL_A_COALESCE_USE_CQE_MODE_TX: i32 = ETHTOOL_A_COALESCE_RATE_SAMPLE_INTERVAL + 1;
pub const ETHTOOL_A_COALESCE_USE_CQE_MODE_RX: i32 = ETHTOOL_A_COALESCE_USE_CQE_MODE_TX + 1;
pub const ETHTOOL_A_COALESCE_TX_AGGR_MAX_BYTES: i32 = ETHTOOL_A_COALESCE_USE_CQE_MODE_RX + 1;
pub const ETHTOOL_A_COALESCE_TX_AGGR_MAX_FRAMES: i32 = ETHTOOL_A_COALESCE_TX_AGGR_MAX_BYTES + 1;
pub const ETHTOOL_A_COALESCE_TX_AGGR_TIME_USECS: i32 = ETHTOOL_A_COALESCE_TX_AGGR_MAX_FRAMES + 1;
pub const ETHTOOL_A_COALESCE_RX_PROFILE: i32 = ETHTOOL_A_COALESCE_TX_AGGR_TIME_USECS + 1;
pub const ETHTOOL_A_COALESCE_TX_PROFILE: i32 = ETHTOOL_A_COALESCE_RX_PROFILE + 1;
pub const ETHTOOL_A_COALESCE_RX_CQE_FRAMES: i32 = ETHTOOL_A_COALESCE_TX_PROFILE + 1;
pub const ETHTOOL_A_COALESCE_RX_CQE_NSECS: i32 = ETHTOOL_A_COALESCE_RX_CQE_FRAMES + 1;
pub const __ETHTOOL_A_COALESCE_CNT: i32 = ETHTOOL_A_COALESCE_RX_CQE_NSECS + 1;
pub const ETHTOOL_A_COALESCE_MAX: i32 = (__ETHTOOL_A_COALESCE_CNT - 1);

pub const ETHTOOL_A_PAUSE_STAT_UNSPEC: i32 = 0;
pub const ETHTOOL_A_PAUSE_STAT_PAD: i32 = ETHTOOL_A_PAUSE_STAT_UNSPEC + 1;
pub const ETHTOOL_A_PAUSE_STAT_TX_FRAMES: i32 = ETHTOOL_A_PAUSE_STAT_PAD + 1;
pub const ETHTOOL_A_PAUSE_STAT_RX_FRAMES: i32 = ETHTOOL_A_PAUSE_STAT_TX_FRAMES + 1;
pub const ETHTOOL_A_PAUSE_STAT_TX_PAUSE_STORM_EVENTS: i32 = ETHTOOL_A_PAUSE_STAT_RX_FRAMES + 1;
pub const __ETHTOOL_A_PAUSE_STAT_CNT: i32 = ETHTOOL_A_PAUSE_STAT_TX_PAUSE_STORM_EVENTS + 1;
pub const ETHTOOL_A_PAUSE_STAT_MAX: i32 = (__ETHTOOL_A_PAUSE_STAT_CNT - 1);

pub const ETHTOOL_A_PAUSE_UNSPEC: i32 = 0;
pub const ETHTOOL_A_PAUSE_HEADER: i32 = ETHTOOL_A_PAUSE_UNSPEC + 1;
pub const ETHTOOL_A_PAUSE_AUTONEG: i32 = ETHTOOL_A_PAUSE_HEADER + 1;
pub const ETHTOOL_A_PAUSE_RX: i32 = ETHTOOL_A_PAUSE_AUTONEG + 1;
pub const ETHTOOL_A_PAUSE_TX: i32 = ETHTOOL_A_PAUSE_RX + 1;
pub const ETHTOOL_A_PAUSE_STATS: i32 = ETHTOOL_A_PAUSE_TX + 1;
pub const ETHTOOL_A_PAUSE_STATS_SRC: i32 = ETHTOOL_A_PAUSE_STATS + 1;
pub const __ETHTOOL_A_PAUSE_CNT: i32 = ETHTOOL_A_PAUSE_STATS_SRC + 1;
pub const ETHTOOL_A_PAUSE_MAX: i32 = (__ETHTOOL_A_PAUSE_CNT - 1);

pub const ETHTOOL_A_EEE_UNSPEC: i32 = 0;
pub const ETHTOOL_A_EEE_HEADER: i32 = ETHTOOL_A_EEE_UNSPEC + 1;
pub const ETHTOOL_A_EEE_MODES_OURS: i32 = ETHTOOL_A_EEE_HEADER + 1;
pub const ETHTOOL_A_EEE_MODES_PEER: i32 = ETHTOOL_A_EEE_MODES_OURS + 1;
pub const ETHTOOL_A_EEE_ACTIVE: i32 = ETHTOOL_A_EEE_MODES_PEER + 1;
pub const ETHTOOL_A_EEE_ENABLED: i32 = ETHTOOL_A_EEE_ACTIVE + 1;
pub const ETHTOOL_A_EEE_TX_LPI_ENABLED: i32 = ETHTOOL_A_EEE_ENABLED + 1;
pub const ETHTOOL_A_EEE_TX_LPI_TIMER: i32 = ETHTOOL_A_EEE_TX_LPI_ENABLED + 1;
pub const __ETHTOOL_A_EEE_CNT: i32 = ETHTOOL_A_EEE_TX_LPI_TIMER + 1;
pub const ETHTOOL_A_EEE_MAX: i32 = (__ETHTOOL_A_EEE_CNT - 1);

pub const ETHTOOL_A_TS_STAT_UNSPEC: i32 = 0;
pub const ETHTOOL_A_TS_STAT_TX_PKTS: i32 = ETHTOOL_A_TS_STAT_UNSPEC + 1;
pub const ETHTOOL_A_TS_STAT_TX_LOST: i32 = ETHTOOL_A_TS_STAT_TX_PKTS + 1;
pub const ETHTOOL_A_TS_STAT_TX_ERR: i32 = ETHTOOL_A_TS_STAT_TX_LOST + 1;
pub const ETHTOOL_A_TS_STAT_TX_ONESTEP_PKTS_UNCONFIRMED: i32 = ETHTOOL_A_TS_STAT_TX_ERR + 1;
pub const __ETHTOOL_A_TS_STAT_CNT: i32 = ETHTOOL_A_TS_STAT_TX_ONESTEP_PKTS_UNCONFIRMED + 1;
pub const ETHTOOL_A_TS_STAT_MAX: i32 = (__ETHTOOL_A_TS_STAT_CNT - 1);

pub const ETHTOOL_A_TS_HWTSTAMP_PROVIDER_UNSPEC: i32 = 0;
pub const ETHTOOL_A_TS_HWTSTAMP_PROVIDER_INDEX: i32 = ETHTOOL_A_TS_HWTSTAMP_PROVIDER_UNSPEC + 1;
pub const ETHTOOL_A_TS_HWTSTAMP_PROVIDER_QUALIFIER: i32 = ETHTOOL_A_TS_HWTSTAMP_PROVIDER_INDEX + 1;
pub const __ETHTOOL_A_TS_HWTSTAMP_PROVIDER_CNT: i32 = ETHTOOL_A_TS_HWTSTAMP_PROVIDER_QUALIFIER + 1;
pub const ETHTOOL_A_TS_HWTSTAMP_PROVIDER_MAX: i32 = (__ETHTOOL_A_TS_HWTSTAMP_PROVIDER_CNT - 1);

pub const ETHTOOL_A_TSINFO_UNSPEC: i32 = 0;
pub const ETHTOOL_A_TSINFO_HEADER: i32 = ETHTOOL_A_TSINFO_UNSPEC + 1;
pub const ETHTOOL_A_TSINFO_TIMESTAMPING: i32 = ETHTOOL_A_TSINFO_HEADER + 1;
pub const ETHTOOL_A_TSINFO_TX_TYPES: i32 = ETHTOOL_A_TSINFO_TIMESTAMPING + 1;
pub const ETHTOOL_A_TSINFO_RX_FILTERS: i32 = ETHTOOL_A_TSINFO_TX_TYPES + 1;
pub const ETHTOOL_A_TSINFO_PHC_INDEX: i32 = ETHTOOL_A_TSINFO_RX_FILTERS + 1;
pub const ETHTOOL_A_TSINFO_STATS: i32 = ETHTOOL_A_TSINFO_PHC_INDEX + 1;
pub const ETHTOOL_A_TSINFO_HWTSTAMP_PROVIDER: i32 = ETHTOOL_A_TSINFO_STATS + 1;
pub const ETHTOOL_A_TSINFO_HWTSTAMP_SOURCE: i32 = ETHTOOL_A_TSINFO_HWTSTAMP_PROVIDER + 1;
pub const ETHTOOL_A_TSINFO_HWTSTAMP_PHYINDEX: i32 = ETHTOOL_A_TSINFO_HWTSTAMP_SOURCE + 1;
pub const __ETHTOOL_A_TSINFO_CNT: i32 = ETHTOOL_A_TSINFO_HWTSTAMP_PHYINDEX + 1;
pub const ETHTOOL_A_TSINFO_MAX: i32 = (__ETHTOOL_A_TSINFO_CNT - 1);

pub const ETHTOOL_A_CABLE_RESULT_UNSPEC: i32 = 0;
pub const ETHTOOL_A_CABLE_RESULT_PAIR: i32 = ETHTOOL_A_CABLE_RESULT_UNSPEC + 1;
pub const ETHTOOL_A_CABLE_RESULT_CODE: i32 = ETHTOOL_A_CABLE_RESULT_PAIR + 1;
pub const ETHTOOL_A_CABLE_RESULT_SRC: i32 = ETHTOOL_A_CABLE_RESULT_CODE + 1;
pub const __ETHTOOL_A_CABLE_RESULT_CNT: i32 = ETHTOOL_A_CABLE_RESULT_SRC + 1;
pub const ETHTOOL_A_CABLE_RESULT_MAX: i32 = (__ETHTOOL_A_CABLE_RESULT_CNT - 1);

pub const ETHTOOL_A_CABLE_FAULT_LENGTH_UNSPEC: i32 = 0;
pub const ETHTOOL_A_CABLE_FAULT_LENGTH_PAIR: i32 = ETHTOOL_A_CABLE_FAULT_LENGTH_UNSPEC + 1;
pub const ETHTOOL_A_CABLE_FAULT_LENGTH_CM: i32 = ETHTOOL_A_CABLE_FAULT_LENGTH_PAIR + 1;
pub const ETHTOOL_A_CABLE_FAULT_LENGTH_SRC: i32 = ETHTOOL_A_CABLE_FAULT_LENGTH_CM + 1;
pub const __ETHTOOL_A_CABLE_FAULT_LENGTH_CNT: i32 = ETHTOOL_A_CABLE_FAULT_LENGTH_SRC + 1;
pub const ETHTOOL_A_CABLE_FAULT_LENGTH_MAX: i32 = (__ETHTOOL_A_CABLE_FAULT_LENGTH_CNT - 1);

pub const ETHTOOL_A_CABLE_NEST_UNSPEC: i32 = 0;
pub const ETHTOOL_A_CABLE_NEST_RESULT: i32 = ETHTOOL_A_CABLE_NEST_UNSPEC + 1;
pub const ETHTOOL_A_CABLE_NEST_FAULT_LENGTH: i32 = ETHTOOL_A_CABLE_NEST_RESULT + 1;
pub const __ETHTOOL_A_CABLE_NEST_CNT: i32 = ETHTOOL_A_CABLE_NEST_FAULT_LENGTH + 1;
pub const ETHTOOL_A_CABLE_NEST_MAX: i32 = (__ETHTOOL_A_CABLE_NEST_CNT - 1);

pub const ETHTOOL_A_CABLE_TEST_UNSPEC: i32 = 0;
pub const ETHTOOL_A_CABLE_TEST_HEADER: i32 = ETHTOOL_A_CABLE_TEST_UNSPEC + 1;
pub const __ETHTOOL_A_CABLE_TEST_CNT: i32 = ETHTOOL_A_CABLE_TEST_HEADER + 1;
pub const ETHTOOL_A_CABLE_TEST_MAX: i32 = (__ETHTOOL_A_CABLE_TEST_CNT - 1);

pub const ETHTOOL_A_CABLE_TEST_NTF_UNSPEC: i32 = 0;
pub const ETHTOOL_A_CABLE_TEST_NTF_HEADER: i32 = ETHTOOL_A_CABLE_TEST_NTF_UNSPEC + 1;
pub const ETHTOOL_A_CABLE_TEST_NTF_STATUS: i32 = ETHTOOL_A_CABLE_TEST_NTF_HEADER + 1;
pub const ETHTOOL_A_CABLE_TEST_NTF_NEST: i32 = ETHTOOL_A_CABLE_TEST_NTF_STATUS + 1;
pub const __ETHTOOL_A_CABLE_TEST_NTF_CNT: i32 = ETHTOOL_A_CABLE_TEST_NTF_NEST + 1;
pub const ETHTOOL_A_CABLE_TEST_NTF_MAX: i32 = (__ETHTOOL_A_CABLE_TEST_NTF_CNT - 1);

pub const ETHTOOL_A_CABLE_TEST_TDR_CFG_UNSPEC: i32 = 0;
pub const ETHTOOL_A_CABLE_TEST_TDR_CFG_FIRST: i32 = ETHTOOL_A_CABLE_TEST_TDR_CFG_UNSPEC + 1;
pub const ETHTOOL_A_CABLE_TEST_TDR_CFG_LAST: i32 = ETHTOOL_A_CABLE_TEST_TDR_CFG_FIRST + 1;
pub const ETHTOOL_A_CABLE_TEST_TDR_CFG_STEP: i32 = ETHTOOL_A_CABLE_TEST_TDR_CFG_LAST + 1;
pub const ETHTOOL_A_CABLE_TEST_TDR_CFG_PAIR: i32 = ETHTOOL_A_CABLE_TEST_TDR_CFG_STEP + 1;
pub const __ETHTOOL_A_CABLE_TEST_TDR_CFG_CNT: i32 = ETHTOOL_A_CABLE_TEST_TDR_CFG_PAIR + 1;
pub const ETHTOOL_A_CABLE_TEST_TDR_CFG_MAX: i32 = (__ETHTOOL_A_CABLE_TEST_TDR_CFG_CNT - 1);

pub const ETHTOOL_A_CABLE_TEST_TDR_NTF_UNSPEC: i32 = 0;
pub const ETHTOOL_A_CABLE_TEST_TDR_NTF_HEADER: i32 = ETHTOOL_A_CABLE_TEST_TDR_NTF_UNSPEC + 1;
pub const ETHTOOL_A_CABLE_TEST_TDR_NTF_STATUS: i32 = ETHTOOL_A_CABLE_TEST_TDR_NTF_HEADER + 1;
pub const ETHTOOL_A_CABLE_TEST_TDR_NTF_NEST: i32 = ETHTOOL_A_CABLE_TEST_TDR_NTF_STATUS + 1;
pub const __ETHTOOL_A_CABLE_TEST_TDR_NTF_CNT: i32 = ETHTOOL_A_CABLE_TEST_TDR_NTF_NEST + 1;
pub const ETHTOOL_A_CABLE_TEST_TDR_NTF_MAX: i32 = (__ETHTOOL_A_CABLE_TEST_TDR_NTF_CNT - 1);

pub const ETHTOOL_A_CABLE_TEST_TDR_UNSPEC: i32 = 0;
pub const ETHTOOL_A_CABLE_TEST_TDR_HEADER: i32 = ETHTOOL_A_CABLE_TEST_TDR_UNSPEC + 1;
pub const ETHTOOL_A_CABLE_TEST_TDR_CFG: i32 = ETHTOOL_A_CABLE_TEST_TDR_HEADER + 1;
pub const __ETHTOOL_A_CABLE_TEST_TDR_CNT: i32 = ETHTOOL_A_CABLE_TEST_TDR_CFG + 1;
pub const ETHTOOL_A_CABLE_TEST_TDR_MAX: i32 = (__ETHTOOL_A_CABLE_TEST_TDR_CNT - 1);

pub const ETHTOOL_A_TUNNEL_UDP_ENTRY_UNSPEC: i32 = 0;
pub const ETHTOOL_A_TUNNEL_UDP_ENTRY_PORT: i32 = ETHTOOL_A_TUNNEL_UDP_ENTRY_UNSPEC + 1;
pub const ETHTOOL_A_TUNNEL_UDP_ENTRY_TYPE: i32 = ETHTOOL_A_TUNNEL_UDP_ENTRY_PORT + 1;
pub const __ETHTOOL_A_TUNNEL_UDP_ENTRY_CNT: i32 = ETHTOOL_A_TUNNEL_UDP_ENTRY_TYPE + 1;
pub const ETHTOOL_A_TUNNEL_UDP_ENTRY_MAX: i32 = (__ETHTOOL_A_TUNNEL_UDP_ENTRY_CNT - 1);

pub const ETHTOOL_A_TUNNEL_UDP_TABLE_UNSPEC: i32 = 0;
pub const ETHTOOL_A_TUNNEL_UDP_TABLE_SIZE: i32 = ETHTOOL_A_TUNNEL_UDP_TABLE_UNSPEC + 1;
pub const ETHTOOL_A_TUNNEL_UDP_TABLE_TYPES: i32 = ETHTOOL_A_TUNNEL_UDP_TABLE_SIZE + 1;
pub const ETHTOOL_A_TUNNEL_UDP_TABLE_ENTRY: i32 = ETHTOOL_A_TUNNEL_UDP_TABLE_TYPES + 1;
pub const __ETHTOOL_A_TUNNEL_UDP_TABLE_CNT: i32 = ETHTOOL_A_TUNNEL_UDP_TABLE_ENTRY + 1;
pub const ETHTOOL_A_TUNNEL_UDP_TABLE_MAX: i32 = (__ETHTOOL_A_TUNNEL_UDP_TABLE_CNT - 1);

pub const ETHTOOL_A_TUNNEL_UDP_UNSPEC: i32 = 0;
pub const ETHTOOL_A_TUNNEL_UDP_TABLE: i32 = ETHTOOL_A_TUNNEL_UDP_UNSPEC + 1;
pub const __ETHTOOL_A_TUNNEL_UDP_CNT: i32 = ETHTOOL_A_TUNNEL_UDP_TABLE + 1;
pub const ETHTOOL_A_TUNNEL_UDP_MAX: i32 = (__ETHTOOL_A_TUNNEL_UDP_CNT - 1);

pub const ETHTOOL_A_TUNNEL_INFO_UNSPEC: i32 = 0;
pub const ETHTOOL_A_TUNNEL_INFO_HEADER: i32 = ETHTOOL_A_TUNNEL_INFO_UNSPEC + 1;
pub const ETHTOOL_A_TUNNEL_INFO_UDP_PORTS: i32 = ETHTOOL_A_TUNNEL_INFO_HEADER + 1;
pub const __ETHTOOL_A_TUNNEL_INFO_CNT: i32 = ETHTOOL_A_TUNNEL_INFO_UDP_PORTS + 1;
pub const ETHTOOL_A_TUNNEL_INFO_MAX: i32 = (__ETHTOOL_A_TUNNEL_INFO_CNT - 1);

pub const ETHTOOL_A_FEC_HIST_PAD: i32 = 1;
pub const ETHTOOL_A_FEC_HIST_BIN_LOW: i32 = ETHTOOL_A_FEC_HIST_PAD + 1;
pub const ETHTOOL_A_FEC_HIST_BIN_HIGH: i32 = ETHTOOL_A_FEC_HIST_BIN_LOW + 1;
pub const ETHTOOL_A_FEC_HIST_BIN_VAL: i32 = ETHTOOL_A_FEC_HIST_BIN_HIGH + 1;
pub const ETHTOOL_A_FEC_HIST_BIN_VAL_PER_LANE: i32 = ETHTOOL_A_FEC_HIST_BIN_VAL + 1;
pub const __ETHTOOL_A_FEC_HIST_CNT: i32 = ETHTOOL_A_FEC_HIST_BIN_VAL_PER_LANE + 1;
pub const ETHTOOL_A_FEC_HIST_MAX: i32 = (__ETHTOOL_A_FEC_HIST_CNT - 1);

pub const ETHTOOL_A_FEC_STAT_UNSPEC: i32 = 0;
pub const ETHTOOL_A_FEC_STAT_PAD: i32 = ETHTOOL_A_FEC_STAT_UNSPEC + 1;
pub const ETHTOOL_A_FEC_STAT_CORRECTED: i32 = ETHTOOL_A_FEC_STAT_PAD + 1;
pub const ETHTOOL_A_FEC_STAT_UNCORR: i32 = ETHTOOL_A_FEC_STAT_CORRECTED + 1;
pub const ETHTOOL_A_FEC_STAT_CORR_BITS: i32 = ETHTOOL_A_FEC_STAT_UNCORR + 1;
pub const ETHTOOL_A_FEC_STAT_HIST: i32 = ETHTOOL_A_FEC_STAT_CORR_BITS + 1;
pub const __ETHTOOL_A_FEC_STAT_CNT: i32 = ETHTOOL_A_FEC_STAT_HIST + 1;
pub const ETHTOOL_A_FEC_STAT_MAX: i32 = (__ETHTOOL_A_FEC_STAT_CNT - 1);

pub const ETHTOOL_A_FEC_UNSPEC: i32 = 0;
pub const ETHTOOL_A_FEC_HEADER: i32 = ETHTOOL_A_FEC_UNSPEC + 1;
pub const ETHTOOL_A_FEC_MODES: i32 = ETHTOOL_A_FEC_HEADER + 1;
pub const ETHTOOL_A_FEC_AUTO: i32 = ETHTOOL_A_FEC_MODES + 1;
pub const ETHTOOL_A_FEC_ACTIVE: i32 = ETHTOOL_A_FEC_AUTO + 1;
pub const ETHTOOL_A_FEC_STATS: i32 = ETHTOOL_A_FEC_ACTIVE + 1;
pub const __ETHTOOL_A_FEC_CNT: i32 = ETHTOOL_A_FEC_STATS + 1;
pub const ETHTOOL_A_FEC_MAX: i32 = (__ETHTOOL_A_FEC_CNT - 1);

pub const ETHTOOL_A_MODULE_EEPROM_UNSPEC: i32 = 0;
pub const ETHTOOL_A_MODULE_EEPROM_HEADER: i32 = ETHTOOL_A_MODULE_EEPROM_UNSPEC + 1;
pub const ETHTOOL_A_MODULE_EEPROM_OFFSET: i32 = ETHTOOL_A_MODULE_EEPROM_HEADER + 1;
pub const ETHTOOL_A_MODULE_EEPROM_LENGTH: i32 = ETHTOOL_A_MODULE_EEPROM_OFFSET + 1;
pub const ETHTOOL_A_MODULE_EEPROM_PAGE: i32 = ETHTOOL_A_MODULE_EEPROM_LENGTH + 1;
pub const ETHTOOL_A_MODULE_EEPROM_BANK: i32 = ETHTOOL_A_MODULE_EEPROM_PAGE + 1;
pub const ETHTOOL_A_MODULE_EEPROM_I2C_ADDRESS: i32 = ETHTOOL_A_MODULE_EEPROM_BANK + 1;
pub const ETHTOOL_A_MODULE_EEPROM_DATA: i32 = ETHTOOL_A_MODULE_EEPROM_I2C_ADDRESS + 1;
pub const __ETHTOOL_A_MODULE_EEPROM_CNT: i32 = ETHTOOL_A_MODULE_EEPROM_DATA + 1;
pub const ETHTOOL_A_MODULE_EEPROM_MAX: i32 = (__ETHTOOL_A_MODULE_EEPROM_CNT - 1);

pub const ETHTOOL_A_STATS_GRP_UNSPEC: i32 = 0;
pub const ETHTOOL_A_STATS_GRP_PAD: i32 = ETHTOOL_A_STATS_GRP_UNSPEC + 1;
pub const ETHTOOL_A_STATS_GRP_ID: i32 = ETHTOOL_A_STATS_GRP_PAD + 1;
pub const ETHTOOL_A_STATS_GRP_SS_ID: i32 = ETHTOOL_A_STATS_GRP_ID + 1;
pub const ETHTOOL_A_STATS_GRP_STAT: i32 = ETHTOOL_A_STATS_GRP_SS_ID + 1;
pub const ETHTOOL_A_STATS_GRP_HIST_RX: i32 = ETHTOOL_A_STATS_GRP_STAT + 1;
pub const ETHTOOL_A_STATS_GRP_HIST_TX: i32 = ETHTOOL_A_STATS_GRP_HIST_RX + 1;
pub const ETHTOOL_A_STATS_GRP_HIST_BKT_LOW: i32 = ETHTOOL_A_STATS_GRP_HIST_TX + 1;
pub const ETHTOOL_A_STATS_GRP_HIST_BKT_HI: i32 = ETHTOOL_A_STATS_GRP_HIST_BKT_LOW + 1;
pub const ETHTOOL_A_STATS_GRP_HIST_VAL: i32 = ETHTOOL_A_STATS_GRP_HIST_BKT_HI + 1;
pub const __ETHTOOL_A_STATS_GRP_CNT: i32 = ETHTOOL_A_STATS_GRP_HIST_VAL + 1;
pub const ETHTOOL_A_STATS_GRP_MAX: i32 = (__ETHTOOL_A_STATS_GRP_CNT - 1);

pub const ETHTOOL_A_STATS_UNSPEC: i32 = 0;
pub const ETHTOOL_A_STATS_PAD: i32 = ETHTOOL_A_STATS_UNSPEC + 1;
pub const ETHTOOL_A_STATS_HEADER: i32 = ETHTOOL_A_STATS_PAD + 1;
pub const ETHTOOL_A_STATS_GROUPS: i32 = ETHTOOL_A_STATS_HEADER + 1;
pub const ETHTOOL_A_STATS_GRP: i32 = ETHTOOL_A_STATS_GROUPS + 1;
pub const ETHTOOL_A_STATS_SRC: i32 = ETHTOOL_A_STATS_GRP + 1;
pub const __ETHTOOL_A_STATS_CNT: i32 = ETHTOOL_A_STATS_SRC + 1;
pub const ETHTOOL_A_STATS_MAX: i32 = (__ETHTOOL_A_STATS_CNT - 1);

pub const ETHTOOL_A_PHC_VCLOCKS_UNSPEC: i32 = 0;
pub const ETHTOOL_A_PHC_VCLOCKS_HEADER: i32 = ETHTOOL_A_PHC_VCLOCKS_UNSPEC + 1;
pub const ETHTOOL_A_PHC_VCLOCKS_NUM: i32 = ETHTOOL_A_PHC_VCLOCKS_HEADER + 1;
pub const ETHTOOL_A_PHC_VCLOCKS_INDEX: i32 = ETHTOOL_A_PHC_VCLOCKS_NUM + 1;
pub const __ETHTOOL_A_PHC_VCLOCKS_CNT: i32 = ETHTOOL_A_PHC_VCLOCKS_INDEX + 1;
pub const ETHTOOL_A_PHC_VCLOCKS_MAX: i32 = (__ETHTOOL_A_PHC_VCLOCKS_CNT - 1);

pub const ETHTOOL_A_MODULE_UNSPEC: i32 = 0;
pub const ETHTOOL_A_MODULE_HEADER: i32 = ETHTOOL_A_MODULE_UNSPEC + 1;
pub const ETHTOOL_A_MODULE_POWER_MODE_POLICY: i32 = ETHTOOL_A_MODULE_HEADER + 1;
pub const ETHTOOL_A_MODULE_POWER_MODE: i32 = ETHTOOL_A_MODULE_POWER_MODE_POLICY + 1;
pub const __ETHTOOL_A_MODULE_CNT: i32 = ETHTOOL_A_MODULE_POWER_MODE + 1;
pub const ETHTOOL_A_MODULE_MAX: i32 = (__ETHTOOL_A_MODULE_CNT - 1);

pub const ETHTOOL_A_C33_PSE_PW_LIMIT_UNSPEC: i32 = 0;
pub const ETHTOOL_A_C33_PSE_PW_LIMIT_MIN: i32 = ETHTOOL_A_C33_PSE_PW_LIMIT_UNSPEC + 1;
pub const ETHTOOL_A_C33_PSE_PW_LIMIT_MAX: i32 = ETHTOOL_A_C33_PSE_PW_LIMIT_MIN + 1;
pub const __ETHTOOL_A_C33_PSE_PW_LIMIT_CNT: i32 = ETHTOOL_A_C33_PSE_PW_LIMIT_MAX + 1;
pub const __ETHTOOL_A_C33_PSE_PW_LIMIT_MAX: i32 = (__ETHTOOL_A_C33_PSE_PW_LIMIT_CNT - 1);

pub const ETHTOOL_A_PSE_UNSPEC: i32 = 0;
pub const ETHTOOL_A_PSE_HEADER: i32 = ETHTOOL_A_PSE_UNSPEC + 1;
pub const ETHTOOL_A_PODL_PSE_ADMIN_STATE: i32 = ETHTOOL_A_PSE_HEADER + 1;
pub const ETHTOOL_A_PODL_PSE_ADMIN_CONTROL: i32 = ETHTOOL_A_PODL_PSE_ADMIN_STATE + 1;
pub const ETHTOOL_A_PODL_PSE_PW_D_STATUS: i32 = ETHTOOL_A_PODL_PSE_ADMIN_CONTROL + 1;
pub const ETHTOOL_A_C33_PSE_ADMIN_STATE: i32 = ETHTOOL_A_PODL_PSE_PW_D_STATUS + 1;
pub const ETHTOOL_A_C33_PSE_ADMIN_CONTROL: i32 = ETHTOOL_A_C33_PSE_ADMIN_STATE + 1;
pub const ETHTOOL_A_C33_PSE_PW_D_STATUS: i32 = ETHTOOL_A_C33_PSE_ADMIN_CONTROL + 1;
pub const ETHTOOL_A_C33_PSE_PW_CLASS: i32 = ETHTOOL_A_C33_PSE_PW_D_STATUS + 1;
pub const ETHTOOL_A_C33_PSE_ACTUAL_PW: i32 = ETHTOOL_A_C33_PSE_PW_CLASS + 1;
pub const ETHTOOL_A_C33_PSE_EXT_STATE: i32 = ETHTOOL_A_C33_PSE_ACTUAL_PW + 1;
pub const ETHTOOL_A_C33_PSE_EXT_SUBSTATE: i32 = ETHTOOL_A_C33_PSE_EXT_STATE + 1;
pub const ETHTOOL_A_C33_PSE_AVAIL_PW_LIMIT: i32 = ETHTOOL_A_C33_PSE_EXT_SUBSTATE + 1;
pub const ETHTOOL_A_C33_PSE_PW_LIMIT_RANGES: i32 = ETHTOOL_A_C33_PSE_AVAIL_PW_LIMIT + 1;
pub const ETHTOOL_A_PSE_PW_D_ID: i32 = ETHTOOL_A_C33_PSE_PW_LIMIT_RANGES + 1;
pub const ETHTOOL_A_PSE_PRIO_MAX: i32 = ETHTOOL_A_PSE_PW_D_ID + 1;
pub const ETHTOOL_A_PSE_PRIO: i32 = ETHTOOL_A_PSE_PRIO_MAX + 1;
pub const __ETHTOOL_A_PSE_CNT: i32 = ETHTOOL_A_PSE_PRIO + 1;
pub const ETHTOOL_A_PSE_MAX: i32 = (__ETHTOOL_A_PSE_CNT - 1);

pub const ETHTOOL_A_FLOW_ETHER: i32 = 1;
pub const ETHTOOL_A_FLOW_IP4: i32 = ETHTOOL_A_FLOW_ETHER + 1;
pub const ETHTOOL_A_FLOW_IP6: i32 = ETHTOOL_A_FLOW_IP4 + 1;
pub const ETHTOOL_A_FLOW_TCP4: i32 = ETHTOOL_A_FLOW_IP6 + 1;
pub const ETHTOOL_A_FLOW_TCP6: i32 = ETHTOOL_A_FLOW_TCP4 + 1;
pub const ETHTOOL_A_FLOW_UDP4: i32 = ETHTOOL_A_FLOW_TCP6 + 1;
pub const ETHTOOL_A_FLOW_UDP6: i32 = ETHTOOL_A_FLOW_UDP4 + 1;
pub const ETHTOOL_A_FLOW_SCTP4: i32 = ETHTOOL_A_FLOW_UDP6 + 1;
pub const ETHTOOL_A_FLOW_SCTP6: i32 = ETHTOOL_A_FLOW_SCTP4 + 1;
pub const ETHTOOL_A_FLOW_AH4: i32 = ETHTOOL_A_FLOW_SCTP6 + 1;
pub const ETHTOOL_A_FLOW_AH6: i32 = ETHTOOL_A_FLOW_AH4 + 1;
pub const ETHTOOL_A_FLOW_ESP4: i32 = ETHTOOL_A_FLOW_AH6 + 1;
pub const ETHTOOL_A_FLOW_ESP6: i32 = ETHTOOL_A_FLOW_ESP4 + 1;
pub const ETHTOOL_A_FLOW_AH_ESP4: i32 = ETHTOOL_A_FLOW_ESP6 + 1;
pub const ETHTOOL_A_FLOW_AH_ESP6: i32 = ETHTOOL_A_FLOW_AH_ESP4 + 1;
pub const ETHTOOL_A_FLOW_GTPU4: i32 = ETHTOOL_A_FLOW_AH_ESP6 + 1;
pub const ETHTOOL_A_FLOW_GTPU6: i32 = ETHTOOL_A_FLOW_GTPU4 + 1;
pub const ETHTOOL_A_FLOW_GTPC4: i32 = ETHTOOL_A_FLOW_GTPU6 + 1;
pub const ETHTOOL_A_FLOW_GTPC6: i32 = ETHTOOL_A_FLOW_GTPC4 + 1;
pub const ETHTOOL_A_FLOW_GTPC_TEID4: i32 = ETHTOOL_A_FLOW_GTPC6 + 1;
pub const ETHTOOL_A_FLOW_GTPC_TEID6: i32 = ETHTOOL_A_FLOW_GTPC_TEID4 + 1;
pub const ETHTOOL_A_FLOW_GTPU_EH4: i32 = ETHTOOL_A_FLOW_GTPC_TEID6 + 1;
pub const ETHTOOL_A_FLOW_GTPU_EH6: i32 = ETHTOOL_A_FLOW_GTPU_EH4 + 1;
pub const ETHTOOL_A_FLOW_GTPU_UL4: i32 = ETHTOOL_A_FLOW_GTPU_EH6 + 1;
pub const ETHTOOL_A_FLOW_GTPU_UL6: i32 = ETHTOOL_A_FLOW_GTPU_UL4 + 1;
pub const ETHTOOL_A_FLOW_GTPU_DL4: i32 = ETHTOOL_A_FLOW_GTPU_UL6 + 1;
pub const ETHTOOL_A_FLOW_GTPU_DL6: i32 = ETHTOOL_A_FLOW_GTPU_DL4 + 1;
pub const __ETHTOOL_A_FLOW_CNT: i32 = ETHTOOL_A_FLOW_GTPU_DL6 + 1;
pub const ETHTOOL_A_FLOW_MAX: i32 = (__ETHTOOL_A_FLOW_CNT - 1);

pub const ETHTOOL_A_RSS_UNSPEC: i32 = 0;
pub const ETHTOOL_A_RSS_HEADER: i32 = ETHTOOL_A_RSS_UNSPEC + 1;
pub const ETHTOOL_A_RSS_CONTEXT: i32 = ETHTOOL_A_RSS_HEADER + 1;
pub const ETHTOOL_A_RSS_HFUNC: i32 = ETHTOOL_A_RSS_CONTEXT + 1;
pub const ETHTOOL_A_RSS_INDIR: i32 = ETHTOOL_A_RSS_HFUNC + 1;
pub const ETHTOOL_A_RSS_HKEY: i32 = ETHTOOL_A_RSS_INDIR + 1;
pub const ETHTOOL_A_RSS_INPUT_XFRM: i32 = ETHTOOL_A_RSS_HKEY + 1;
pub const ETHTOOL_A_RSS_START_CONTEXT: i32 = ETHTOOL_A_RSS_INPUT_XFRM + 1;
pub const ETHTOOL_A_RSS_FLOW_HASH: i32 = ETHTOOL_A_RSS_START_CONTEXT + 1;
pub const __ETHTOOL_A_RSS_CNT: i32 = ETHTOOL_A_RSS_FLOW_HASH + 1;
pub const ETHTOOL_A_RSS_MAX: i32 = (__ETHTOOL_A_RSS_CNT - 1);

pub const ETHTOOL_A_PLCA_UNSPEC: i32 = 0;
pub const ETHTOOL_A_PLCA_HEADER: i32 = ETHTOOL_A_PLCA_UNSPEC + 1;
pub const ETHTOOL_A_PLCA_VERSION: i32 = ETHTOOL_A_PLCA_HEADER + 1;
pub const ETHTOOL_A_PLCA_ENABLED: i32 = ETHTOOL_A_PLCA_VERSION + 1;
pub const ETHTOOL_A_PLCA_STATUS: i32 = ETHTOOL_A_PLCA_ENABLED + 1;
pub const ETHTOOL_A_PLCA_NODE_CNT: i32 = ETHTOOL_A_PLCA_STATUS + 1;
pub const ETHTOOL_A_PLCA_NODE_ID: i32 = ETHTOOL_A_PLCA_NODE_CNT + 1;
pub const ETHTOOL_A_PLCA_TO_TMR: i32 = ETHTOOL_A_PLCA_NODE_ID + 1;
pub const ETHTOOL_A_PLCA_BURST_CNT: i32 = ETHTOOL_A_PLCA_TO_TMR + 1;
pub const ETHTOOL_A_PLCA_BURST_TMR: i32 = ETHTOOL_A_PLCA_BURST_CNT + 1;
pub const __ETHTOOL_A_PLCA_CNT: i32 = ETHTOOL_A_PLCA_BURST_TMR + 1;
pub const ETHTOOL_A_PLCA_MAX: i32 = (__ETHTOOL_A_PLCA_CNT - 1);

pub const ETHTOOL_A_MODULE_FW_FLASH_UNSPEC: i32 = 0;
pub const ETHTOOL_A_MODULE_FW_FLASH_HEADER: i32 = ETHTOOL_A_MODULE_FW_FLASH_UNSPEC + 1;
pub const ETHTOOL_A_MODULE_FW_FLASH_FILE_NAME: i32 = ETHTOOL_A_MODULE_FW_FLASH_HEADER + 1;
pub const ETHTOOL_A_MODULE_FW_FLASH_PASSWORD: i32 = ETHTOOL_A_MODULE_FW_FLASH_FILE_NAME + 1;
pub const ETHTOOL_A_MODULE_FW_FLASH_STATUS: i32 = ETHTOOL_A_MODULE_FW_FLASH_PASSWORD + 1;
pub const ETHTOOL_A_MODULE_FW_FLASH_STATUS_MSG: i32 = ETHTOOL_A_MODULE_FW_FLASH_STATUS + 1;
pub const ETHTOOL_A_MODULE_FW_FLASH_DONE: i32 = ETHTOOL_A_MODULE_FW_FLASH_STATUS_MSG + 1;
pub const ETHTOOL_A_MODULE_FW_FLASH_TOTAL: i32 = ETHTOOL_A_MODULE_FW_FLASH_DONE + 1;
pub const __ETHTOOL_A_MODULE_FW_FLASH_CNT: i32 = ETHTOOL_A_MODULE_FW_FLASH_TOTAL + 1;
pub const ETHTOOL_A_MODULE_FW_FLASH_MAX: i32 = (__ETHTOOL_A_MODULE_FW_FLASH_CNT - 1);

pub const ETHTOOL_A_PHY_UNSPEC: i32 = 0;
pub const ETHTOOL_A_PHY_HEADER: i32 = ETHTOOL_A_PHY_UNSPEC + 1;
pub const ETHTOOL_A_PHY_INDEX: i32 = ETHTOOL_A_PHY_HEADER + 1;
pub const ETHTOOL_A_PHY_DRVNAME: i32 = ETHTOOL_A_PHY_INDEX + 1;
pub const ETHTOOL_A_PHY_NAME: i32 = ETHTOOL_A_PHY_DRVNAME + 1;
pub const ETHTOOL_A_PHY_UPSTREAM_TYPE: i32 = ETHTOOL_A_PHY_NAME + 1;
pub const ETHTOOL_A_PHY_UPSTREAM_INDEX: i32 = ETHTOOL_A_PHY_UPSTREAM_TYPE + 1;
pub const ETHTOOL_A_PHY_UPSTREAM_SFP_NAME: i32 = ETHTOOL_A_PHY_UPSTREAM_INDEX + 1;
pub const ETHTOOL_A_PHY_DOWNSTREAM_SFP_NAME: i32 = ETHTOOL_A_PHY_UPSTREAM_SFP_NAME + 1;
pub const __ETHTOOL_A_PHY_CNT: i32 = ETHTOOL_A_PHY_DOWNSTREAM_SFP_NAME + 1;
pub const ETHTOOL_A_PHY_MAX: i32 = (__ETHTOOL_A_PHY_CNT - 1);

pub const ETHTOOL_A_TSCONFIG_UNSPEC: i32 = 0;
pub const ETHTOOL_A_TSCONFIG_HEADER: i32 = ETHTOOL_A_TSCONFIG_UNSPEC + 1;
pub const ETHTOOL_A_TSCONFIG_HWTSTAMP_PROVIDER: i32 = ETHTOOL_A_TSCONFIG_HEADER + 1;
pub const ETHTOOL_A_TSCONFIG_TX_TYPES: i32 = ETHTOOL_A_TSCONFIG_HWTSTAMP_PROVIDER + 1;
pub const ETHTOOL_A_TSCONFIG_RX_FILTERS: i32 = ETHTOOL_A_TSCONFIG_TX_TYPES + 1;
pub const ETHTOOL_A_TSCONFIG_HWTSTAMP_FLAGS: i32 = ETHTOOL_A_TSCONFIG_RX_FILTERS + 1;
pub const __ETHTOOL_A_TSCONFIG_CNT: i32 = ETHTOOL_A_TSCONFIG_HWTSTAMP_FLAGS + 1;
pub const ETHTOOL_A_TSCONFIG_MAX: i32 = (__ETHTOOL_A_TSCONFIG_CNT - 1);

pub const ETHTOOL_A_PSE_NTF_HEADER: i32 = 1;
pub const ETHTOOL_A_PSE_NTF_EVENTS: i32 = ETHTOOL_A_PSE_NTF_HEADER + 1;
pub const __ETHTOOL_A_PSE_NTF_CNT: i32 = ETHTOOL_A_PSE_NTF_EVENTS + 1;
pub const ETHTOOL_A_PSE_NTF_MAX: i32 = (__ETHTOOL_A_PSE_NTF_CNT - 1);

pub const ETHTOOL_A_MSE_CAPABILITIES_MAX_AVERAGE_MSE: i32 = 1;
pub const ETHTOOL_A_MSE_CAPABILITIES_MAX_PEAK_MSE: i32 = ETHTOOL_A_MSE_CAPABILITIES_MAX_AVERAGE_MSE + 1;
pub const ETHTOOL_A_MSE_CAPABILITIES_REFRESH_RATE_PS: i32 = ETHTOOL_A_MSE_CAPABILITIES_MAX_PEAK_MSE + 1;
pub const ETHTOOL_A_MSE_CAPABILITIES_NUM_SYMBOLS: i32 = ETHTOOL_A_MSE_CAPABILITIES_REFRESH_RATE_PS + 1;
pub const __ETHTOOL_A_MSE_CAPABILITIES_CNT: i32 = ETHTOOL_A_MSE_CAPABILITIES_NUM_SYMBOLS + 1;
pub const ETHTOOL_A_MSE_CAPABILITIES_MAX: i32 = (__ETHTOOL_A_MSE_CAPABILITIES_CNT - 1);

pub const ETHTOOL_A_MSE_SNAPSHOT_AVERAGE_MSE: i32 = 1;
pub const ETHTOOL_A_MSE_SNAPSHOT_PEAK_MSE: i32 = ETHTOOL_A_MSE_SNAPSHOT_AVERAGE_MSE + 1;
pub const ETHTOOL_A_MSE_SNAPSHOT_WORST_PEAK_MSE: i32 = ETHTOOL_A_MSE_SNAPSHOT_PEAK_MSE + 1;
pub const __ETHTOOL_A_MSE_SNAPSHOT_CNT: i32 = ETHTOOL_A_MSE_SNAPSHOT_WORST_PEAK_MSE + 1;
pub const ETHTOOL_A_MSE_SNAPSHOT_MAX: i32 = (__ETHTOOL_A_MSE_SNAPSHOT_CNT - 1);

pub const ETHTOOL_A_MSE_HEADER: i32 = 1;
pub const ETHTOOL_A_MSE_CAPABILITIES: i32 = ETHTOOL_A_MSE_HEADER + 1;
pub const ETHTOOL_A_MSE_CHANNEL_A: i32 = ETHTOOL_A_MSE_CAPABILITIES + 1;
pub const ETHTOOL_A_MSE_CHANNEL_B: i32 = ETHTOOL_A_MSE_CHANNEL_A + 1;
pub const ETHTOOL_A_MSE_CHANNEL_C: i32 = ETHTOOL_A_MSE_CHANNEL_B + 1;
pub const ETHTOOL_A_MSE_CHANNEL_D: i32 = ETHTOOL_A_MSE_CHANNEL_C + 1;
pub const ETHTOOL_A_MSE_WORST_CHANNEL: i32 = ETHTOOL_A_MSE_CHANNEL_D + 1;
pub const ETHTOOL_A_MSE_LINK: i32 = ETHTOOL_A_MSE_WORST_CHANNEL + 1;
pub const __ETHTOOL_A_MSE_CNT: i32 = ETHTOOL_A_MSE_LINK + 1;
pub const ETHTOOL_A_MSE_MAX: i32 = (__ETHTOOL_A_MSE_CNT - 1);

pub const ETHTOOL_MSG_USER_NONE: i32 = 0;
pub const ETHTOOL_MSG_STRSET_GET: i32 = 1;
pub const ETHTOOL_MSG_LINKINFO_GET: i32 = ETHTOOL_MSG_STRSET_GET + 1;
pub const ETHTOOL_MSG_LINKINFO_SET: i32 = ETHTOOL_MSG_LINKINFO_GET + 1;
pub const ETHTOOL_MSG_LINKMODES_GET: i32 = ETHTOOL_MSG_LINKINFO_SET + 1;
pub const ETHTOOL_MSG_LINKMODES_SET: i32 = ETHTOOL_MSG_LINKMODES_GET + 1;
pub const ETHTOOL_MSG_LINKSTATE_GET: i32 = ETHTOOL_MSG_LINKMODES_SET + 1;
pub const ETHTOOL_MSG_DEBUG_GET: i32 = ETHTOOL_MSG_LINKSTATE_GET + 1;
pub const ETHTOOL_MSG_DEBUG_SET: i32 = ETHTOOL_MSG_DEBUG_GET + 1;
pub const ETHTOOL_MSG_WOL_GET: i32 = ETHTOOL_MSG_DEBUG_SET + 1;
pub const ETHTOOL_MSG_WOL_SET: i32 = ETHTOOL_MSG_WOL_GET + 1;
pub const ETHTOOL_MSG_FEATURES_GET: i32 = ETHTOOL_MSG_WOL_SET + 1;
pub const ETHTOOL_MSG_FEATURES_SET: i32 = ETHTOOL_MSG_FEATURES_GET + 1;
pub const ETHTOOL_MSG_PRIVFLAGS_GET: i32 = ETHTOOL_MSG_FEATURES_SET + 1;
pub const ETHTOOL_MSG_PRIVFLAGS_SET: i32 = ETHTOOL_MSG_PRIVFLAGS_GET + 1;
pub const ETHTOOL_MSG_RINGS_GET: i32 = ETHTOOL_MSG_PRIVFLAGS_SET + 1;
pub const ETHTOOL_MSG_RINGS_SET: i32 = ETHTOOL_MSG_RINGS_GET + 1;
pub const ETHTOOL_MSG_CHANNELS_GET: i32 = ETHTOOL_MSG_RINGS_SET + 1;
pub const ETHTOOL_MSG_CHANNELS_SET: i32 = ETHTOOL_MSG_CHANNELS_GET + 1;
pub const ETHTOOL_MSG_COALESCE_GET: i32 = ETHTOOL_MSG_CHANNELS_SET + 1;
pub const ETHTOOL_MSG_COALESCE_SET: i32 = ETHTOOL_MSG_COALESCE_GET + 1;
pub const ETHTOOL_MSG_PAUSE_GET: i32 = ETHTOOL_MSG_COALESCE_SET + 1;
pub const ETHTOOL_MSG_PAUSE_SET: i32 = ETHTOOL_MSG_PAUSE_GET + 1;
pub const ETHTOOL_MSG_EEE_GET: i32 = ETHTOOL_MSG_PAUSE_SET + 1;
pub const ETHTOOL_MSG_EEE_SET: i32 = ETHTOOL_MSG_EEE_GET + 1;
pub const ETHTOOL_MSG_TSINFO_GET: i32 = ETHTOOL_MSG_EEE_SET + 1;
pub const ETHTOOL_MSG_CABLE_TEST_ACT: i32 = ETHTOOL_MSG_TSINFO_GET + 1;
pub const ETHTOOL_MSG_CABLE_TEST_TDR_ACT: i32 = ETHTOOL_MSG_CABLE_TEST_ACT + 1;
pub const ETHTOOL_MSG_TUNNEL_INFO_GET: i32 = ETHTOOL_MSG_CABLE_TEST_TDR_ACT + 1;
pub const ETHTOOL_MSG_FEC_GET: i32 = ETHTOOL_MSG_TUNNEL_INFO_GET + 1;
pub const ETHTOOL_MSG_FEC_SET: i32 = ETHTOOL_MSG_FEC_GET + 1;
pub const ETHTOOL_MSG_MODULE_EEPROM_GET: i32 = ETHTOOL_MSG_FEC_SET + 1;
pub const ETHTOOL_MSG_STATS_GET: i32 = ETHTOOL_MSG_MODULE_EEPROM_GET + 1;
pub const ETHTOOL_MSG_PHC_VCLOCKS_GET: i32 = ETHTOOL_MSG_STATS_GET + 1;
pub const ETHTOOL_MSG_MODULE_GET: i32 = ETHTOOL_MSG_PHC_VCLOCKS_GET + 1;
pub const ETHTOOL_MSG_MODULE_SET: i32 = ETHTOOL_MSG_MODULE_GET + 1;
pub const ETHTOOL_MSG_PSE_GET: i32 = ETHTOOL_MSG_MODULE_SET + 1;
pub const ETHTOOL_MSG_PSE_SET: i32 = ETHTOOL_MSG_PSE_GET + 1;
pub const ETHTOOL_MSG_RSS_GET: i32 = ETHTOOL_MSG_PSE_SET + 1;
pub const ETHTOOL_MSG_PLCA_GET_CFG: i32 = ETHTOOL_MSG_RSS_GET + 1;
pub const ETHTOOL_MSG_PLCA_SET_CFG: i32 = ETHTOOL_MSG_PLCA_GET_CFG + 1;
pub const ETHTOOL_MSG_PLCA_GET_STATUS: i32 = ETHTOOL_MSG_PLCA_SET_CFG + 1;
pub const ETHTOOL_MSG_MM_GET: i32 = ETHTOOL_MSG_PLCA_GET_STATUS + 1;
pub const ETHTOOL_MSG_MM_SET: i32 = ETHTOOL_MSG_MM_GET + 1;
pub const ETHTOOL_MSG_MODULE_FW_FLASH_ACT: i32 = ETHTOOL_MSG_MM_SET + 1;
pub const ETHTOOL_MSG_PHY_GET: i32 = ETHTOOL_MSG_MODULE_FW_FLASH_ACT + 1;
pub const ETHTOOL_MSG_TSCONFIG_GET: i32 = ETHTOOL_MSG_PHY_GET + 1;
pub const ETHTOOL_MSG_TSCONFIG_SET: i32 = ETHTOOL_MSG_TSCONFIG_GET + 1;
pub const ETHTOOL_MSG_RSS_SET: i32 = ETHTOOL_MSG_TSCONFIG_SET + 1;
pub const ETHTOOL_MSG_RSS_CREATE_ACT: i32 = ETHTOOL_MSG_RSS_SET + 1;
pub const ETHTOOL_MSG_RSS_DELETE_ACT: i32 = ETHTOOL_MSG_RSS_CREATE_ACT + 1;
pub const ETHTOOL_MSG_MSE_GET: i32 = ETHTOOL_MSG_RSS_DELETE_ACT + 1;
pub const __ETHTOOL_MSG_USER_CNT: i32 = ETHTOOL_MSG_MSE_GET + 1;
pub const ETHTOOL_MSG_USER_MAX: i32 = (__ETHTOOL_MSG_USER_CNT - 1);

pub const ETHTOOL_MSG_KERNEL_NONE: i32 = 0;
pub const ETHTOOL_MSG_STRSET_GET_REPLY: i32 = 1;
pub const ETHTOOL_MSG_LINKINFO_GET_REPLY: i32 = ETHTOOL_MSG_STRSET_GET_REPLY + 1;
pub const ETHTOOL_MSG_LINKINFO_NTF: i32 = ETHTOOL_MSG_LINKINFO_GET_REPLY + 1;
pub const ETHTOOL_MSG_LINKMODES_GET_REPLY: i32 = ETHTOOL_MSG_LINKINFO_NTF + 1;
pub const ETHTOOL_MSG_LINKMODES_NTF: i32 = ETHTOOL_MSG_LINKMODES_GET_REPLY + 1;
pub const ETHTOOL_MSG_LINKSTATE_GET_REPLY: i32 = ETHTOOL_MSG_LINKMODES_NTF + 1;
pub const ETHTOOL_MSG_DEBUG_GET_REPLY: i32 = ETHTOOL_MSG_LINKSTATE_GET_REPLY + 1;
pub const ETHTOOL_MSG_DEBUG_NTF: i32 = ETHTOOL_MSG_DEBUG_GET_REPLY + 1;
pub const ETHTOOL_MSG_WOL_GET_REPLY: i32 = ETHTOOL_MSG_DEBUG_NTF + 1;
pub const ETHTOOL_MSG_WOL_NTF: i32 = ETHTOOL_MSG_WOL_GET_REPLY + 1;
pub const ETHTOOL_MSG_FEATURES_GET_REPLY: i32 = ETHTOOL_MSG_WOL_NTF + 1;
pub const ETHTOOL_MSG_FEATURES_SET_REPLY: i32 = ETHTOOL_MSG_FEATURES_GET_REPLY + 1;
pub const ETHTOOL_MSG_FEATURES_NTF: i32 = ETHTOOL_MSG_FEATURES_SET_REPLY + 1;
pub const ETHTOOL_MSG_PRIVFLAGS_GET_REPLY: i32 = ETHTOOL_MSG_FEATURES_NTF + 1;
pub const ETHTOOL_MSG_PRIVFLAGS_NTF: i32 = ETHTOOL_MSG_PRIVFLAGS_GET_REPLY + 1;
pub const ETHTOOL_MSG_RINGS_GET_REPLY: i32 = ETHTOOL_MSG_PRIVFLAGS_NTF + 1;
pub const ETHTOOL_MSG_RINGS_NTF: i32 = ETHTOOL_MSG_RINGS_GET_REPLY + 1;
pub const ETHTOOL_MSG_CHANNELS_GET_REPLY: i32 = ETHTOOL_MSG_RINGS_NTF + 1;
pub const ETHTOOL_MSG_CHANNELS_NTF: i32 = ETHTOOL_MSG_CHANNELS_GET_REPLY + 1;
pub const ETHTOOL_MSG_COALESCE_GET_REPLY: i32 = ETHTOOL_MSG_CHANNELS_NTF + 1;
pub const ETHTOOL_MSG_COALESCE_NTF: i32 = ETHTOOL_MSG_COALESCE_GET_REPLY + 1;
pub const ETHTOOL_MSG_PAUSE_GET_REPLY: i32 = ETHTOOL_MSG_COALESCE_NTF + 1;
pub const ETHTOOL_MSG_PAUSE_NTF: i32 = ETHTOOL_MSG_PAUSE_GET_REPLY + 1;
pub const ETHTOOL_MSG_EEE_GET_REPLY: i32 = ETHTOOL_MSG_PAUSE_NTF + 1;
pub const ETHTOOL_MSG_EEE_NTF: i32 = ETHTOOL_MSG_EEE_GET_REPLY + 1;
pub const ETHTOOL_MSG_TSINFO_GET_REPLY: i32 = ETHTOOL_MSG_EEE_NTF + 1;
pub const ETHTOOL_MSG_CABLE_TEST_NTF: i32 = ETHTOOL_MSG_TSINFO_GET_REPLY + 1;
pub const ETHTOOL_MSG_CABLE_TEST_TDR_NTF: i32 = ETHTOOL_MSG_CABLE_TEST_NTF + 1;
pub const ETHTOOL_MSG_TUNNEL_INFO_GET_REPLY: i32 = ETHTOOL_MSG_CABLE_TEST_TDR_NTF + 1;
pub const ETHTOOL_MSG_FEC_GET_REPLY: i32 = ETHTOOL_MSG_TUNNEL_INFO_GET_REPLY + 1;
pub const ETHTOOL_MSG_FEC_NTF: i32 = ETHTOOL_MSG_FEC_GET_REPLY + 1;
pub const ETHTOOL_MSG_MODULE_EEPROM_GET_REPLY: i32 = ETHTOOL_MSG_FEC_NTF + 1;
pub const ETHTOOL_MSG_STATS_GET_REPLY: i32 = ETHTOOL_MSG_MODULE_EEPROM_GET_REPLY + 1;
pub const ETHTOOL_MSG_PHC_VCLOCKS_GET_REPLY: i32 = ETHTOOL_MSG_STATS_GET_REPLY + 1;
pub const ETHTOOL_MSG_MODULE_GET_REPLY: i32 = ETHTOOL_MSG_PHC_VCLOCKS_GET_REPLY + 1;
pub const ETHTOOL_MSG_MODULE_NTF: i32 = ETHTOOL_MSG_MODULE_GET_REPLY + 1;
pub const ETHTOOL_MSG_PSE_GET_REPLY: i32 = ETHTOOL_MSG_MODULE_NTF + 1;
pub const ETHTOOL_MSG_RSS_GET_REPLY: i32 = ETHTOOL_MSG_PSE_GET_REPLY + 1;
pub const ETHTOOL_MSG_PLCA_GET_CFG_REPLY: i32 = ETHTOOL_MSG_RSS_GET_REPLY + 1;
pub const ETHTOOL_MSG_PLCA_GET_STATUS_REPLY: i32 = ETHTOOL_MSG_PLCA_GET_CFG_REPLY + 1;
pub const ETHTOOL_MSG_PLCA_NTF: i32 = ETHTOOL_MSG_PLCA_GET_STATUS_REPLY + 1;
pub const ETHTOOL_MSG_MM_GET_REPLY: i32 = ETHTOOL_MSG_PLCA_NTF + 1;
pub const ETHTOOL_MSG_MM_NTF: i32 = ETHTOOL_MSG_MM_GET_REPLY + 1;
pub const ETHTOOL_MSG_MODULE_FW_FLASH_NTF: i32 = ETHTOOL_MSG_MM_NTF + 1;
pub const ETHTOOL_MSG_PHY_GET_REPLY: i32 = ETHTOOL_MSG_MODULE_FW_FLASH_NTF + 1;
pub const ETHTOOL_MSG_PHY_NTF: i32 = ETHTOOL_MSG_PHY_GET_REPLY + 1;
pub const ETHTOOL_MSG_TSCONFIG_GET_REPLY: i32 = ETHTOOL_MSG_PHY_NTF + 1;
pub const ETHTOOL_MSG_TSCONFIG_SET_REPLY: i32 = ETHTOOL_MSG_TSCONFIG_GET_REPLY + 1;
pub const ETHTOOL_MSG_PSE_NTF: i32 = ETHTOOL_MSG_TSCONFIG_SET_REPLY + 1;
pub const ETHTOOL_MSG_RSS_NTF: i32 = ETHTOOL_MSG_PSE_NTF + 1;
pub const ETHTOOL_MSG_RSS_CREATE_ACT_REPLY: i32 = ETHTOOL_MSG_RSS_NTF + 1;
pub const ETHTOOL_MSG_RSS_CREATE_NTF: i32 = ETHTOOL_MSG_RSS_CREATE_ACT_REPLY + 1;
pub const ETHTOOL_MSG_RSS_DELETE_NTF: i32 = ETHTOOL_MSG_RSS_CREATE_NTF + 1;
pub const ETHTOOL_MSG_MSE_GET_REPLY: i32 = ETHTOOL_MSG_RSS_DELETE_NTF + 1;
pub const __ETHTOOL_MSG_KERNEL_CNT: i32 = ETHTOOL_MSG_MSE_GET_REPLY + 1;
pub const ETHTOOL_MSG_KERNEL_MAX: i32 = (__ETHTOOL_MSG_KERNEL_CNT - 1);

pub const ETHTOOL_MCGRP_MONITOR_NAME: &[u8; 8] = b"monitor\0";
