// SPDX-License-Identifier: GPL-2.0-only
//! linux-source: include/uapi/linux/thermal.h
//! linux-revision: 425f94c2954b1fe80ebdbf9b29854e89750355df
//! architectures: common
//! rewrite-task: S016417

pub const THERMAL_NAME_LENGTH: core::ffi::c_int = 20;
pub const THERMAL_THRESHOLD_WAY_UP: core::ffi::c_int = 0x1;
pub const THERMAL_THRESHOLD_WAY_DOWN: core::ffi::c_int = 0x2;

#[repr(C)]
pub enum thermal_device_mode {
    THERMAL_DEVICE_DISABLED = 0,
    THERMAL_DEVICE_ENABLED,
}

#[repr(C)]
pub enum thermal_trip_type {
    THERMAL_TRIP_ACTIVE = 0,
    THERMAL_TRIP_PASSIVE,
    THERMAL_TRIP_HOT,
    THERMAL_TRIP_CRITICAL,
}

pub const THERMAL_GENL_FAMILY_NAME: &str = "thermal";
pub const THERMAL_GENL_VERSION: core::ffi::c_int = 0x02;
pub const THERMAL_GENL_SAMPLING_GROUP_NAME: &str = "sampling";
pub const THERMAL_GENL_EVENT_GROUP_NAME: &str = "event";

#[repr(C)]
pub enum thermal_genl_attr {
    THERMAL_GENL_ATTR_UNSPEC,
    THERMAL_GENL_ATTR_TZ,
    THERMAL_GENL_ATTR_TZ_ID,
    THERMAL_GENL_ATTR_TZ_TEMP,
    THERMAL_GENL_ATTR_TZ_TRIP,
    THERMAL_GENL_ATTR_TZ_TRIP_ID,
    THERMAL_GENL_ATTR_TZ_TRIP_TYPE,
    THERMAL_GENL_ATTR_TZ_TRIP_TEMP,
    THERMAL_GENL_ATTR_TZ_TRIP_HYST,
    THERMAL_GENL_ATTR_TZ_MODE,
    THERMAL_GENL_ATTR_TZ_NAME,
    THERMAL_GENL_ATTR_TZ_CDEV_WEIGHT,
    THERMAL_GENL_ATTR_TZ_GOV,
    THERMAL_GENL_ATTR_TZ_GOV_NAME,
    THERMAL_GENL_ATTR_CDEV,
    THERMAL_GENL_ATTR_CDEV_ID,
    THERMAL_GENL_ATTR_CDEV_CUR_STATE,
    THERMAL_GENL_ATTR_CDEV_MAX_STATE,
    THERMAL_GENL_ATTR_CDEV_NAME,
    THERMAL_GENL_ATTR_GOV_NAME,
    THERMAL_GENL_ATTR_CPU_CAPABILITY,
    THERMAL_GENL_ATTR_CPU_CAPABILITY_ID,
    THERMAL_GENL_ATTR_CPU_CAPABILITY_PERFORMANCE,
    THERMAL_GENL_ATTR_CPU_CAPABILITY_EFFICIENCY,
    THERMAL_GENL_ATTR_THRESHOLD,
    THERMAL_GENL_ATTR_THRESHOLD_TEMP,
    THERMAL_GENL_ATTR_THRESHOLD_DIRECTION,
    THERMAL_GENL_ATTR_TZ_PREV_TEMP,
    __THERMAL_GENL_ATTR_MAX,
}

pub const THERMAL_GENL_ATTR_MAX: core::ffi::c_int =
    thermal_genl_attr::__THERMAL_GENL_ATTR_MAX as core::ffi::c_int - 1;

#[repr(C)]
pub enum thermal_genl_sampling {
    THERMAL_GENL_SAMPLING_TEMP,
    __THERMAL_GENL_SAMPLING_MAX,
}

pub const THERMAL_GENL_SAMPLING_MAX: core::ffi::c_int =
    thermal_genl_sampling::__THERMAL_GENL_SAMPLING_MAX as core::ffi::c_int - 1;

#[repr(C)]
pub enum thermal_genl_event {
    THERMAL_GENL_EVENT_UNSPEC,
    THERMAL_GENL_EVENT_TZ_CREATE,
    THERMAL_GENL_EVENT_TZ_DELETE,
    THERMAL_GENL_EVENT_TZ_DISABLE,
    THERMAL_GENL_EVENT_TZ_ENABLE,
    THERMAL_GENL_EVENT_TZ_TRIP_UP,
    THERMAL_GENL_EVENT_TZ_TRIP_DOWN,
    THERMAL_GENL_EVENT_TZ_TRIP_CHANGE,
    THERMAL_GENL_EVENT_TZ_TRIP_ADD,
    THERMAL_GENL_EVENT_TZ_TRIP_DELETE,
    THERMAL_GENL_EVENT_CDEV_ADD,
    THERMAL_GENL_EVENT_CDEV_DELETE,
    THERMAL_GENL_EVENT_CDEV_STATE_UPDATE,
    THERMAL_GENL_EVENT_TZ_GOV_CHANGE,
    THERMAL_GENL_EVENT_CPU_CAPABILITY_CHANGE,
    THERMAL_GENL_EVENT_THRESHOLD_ADD,
    THERMAL_GENL_EVENT_THRESHOLD_DELETE,
    THERMAL_GENL_EVENT_THRESHOLD_FLUSH,
    THERMAL_GENL_EVENT_THRESHOLD_UP,
    THERMAL_GENL_EVENT_THRESHOLD_DOWN,
    __THERMAL_GENL_EVENT_MAX,
}

pub const THERMAL_GENL_EVENT_MAX: core::ffi::c_int =
    thermal_genl_event::__THERMAL_GENL_EVENT_MAX as core::ffi::c_int - 1;

#[repr(C)]
pub enum thermal_genl_cmd {
    THERMAL_GENL_CMD_UNSPEC,
    THERMAL_GENL_CMD_TZ_GET_ID,
    THERMAL_GENL_CMD_TZ_GET_TRIP,
    THERMAL_GENL_CMD_TZ_GET_TEMP,
    THERMAL_GENL_CMD_TZ_GET_GOV,
    THERMAL_GENL_CMD_TZ_GET_MODE,
    THERMAL_GENL_CMD_CDEV_GET,
    THERMAL_GENL_CMD_THRESHOLD_GET,
    THERMAL_GENL_CMD_THRESHOLD_ADD,
    THERMAL_GENL_CMD_THRESHOLD_DELETE,
    THERMAL_GENL_CMD_THRESHOLD_FLUSH,
    __THERMAL_GENL_CMD_MAX,
}

pub const THERMAL_GENL_CMD_MAX: core::ffi::c_int =
    thermal_genl_cmd::__THERMAL_GENL_CMD_MAX as core::ffi::c_int - 1;
