//! linux-parity: complete
//! linux-source: vendor/linux/drivers/pci
//! test-origin: linux:vendor/linux/drivers/pci
//! Linux PCI (drivers/pci) source coverage.
//!
//! Linux source inventory for this subsystem. This catalog names the
//! `vendor/linux` sources that define PCI driver-core, host-bridge, and module
//! payload behavior. Lupos may provide ABI glue for those entry points, but it
//! must not replace vendor-built PCI drivers with local Rust implementations.
//!
//! Refs:
//! - `vendor/linux/drivers/pci/{access,ats,controller/cadence/pci-j721e,controller/cadence/pci-sky1,controller/cadence/pcie-cadence,controller/cadence/pcie-cadence-ep,controller/cadence/pcie-cadence-host,controller/cadence/pcie-cadence-host-common,controller/cadence/pcie-cadence-host-hpa,controller/cadence/pcie-cadence-hpa,controller/cadence/pcie-cadence-plat,controller/cadence/pcie-sg2042,controller/dwc/pci-dra7xx,controller/dwc/pci-exynos,controller/dwc/pci-imx6,controller/dwc/pci-keystone,controller/dwc/pci-layerscape,controller/dwc/pci-layerscape-ep,controller/dwc/pci-meson,controller/dwc/pcie-al,controller/dwc/pcie-amd-mdb,controller/dwc/pcie-andes-qilai,controller/dwc/pcie-armada8k,controller/dwc/pcie-artpec6,controller/dwc/pcie-designware,controller/dwc/pcie-designware-debugfs,controller/dwc/pcie-designware-ep,controller/dwc/pcie-designware-host,controller/dwc/pcie-designware-plat,controller/dwc/pcie-dw-rockchip,controller/dwc/pcie-eswin,controller/dwc/pcie-fu740,controller/dwc/pcie-hisi,controller/dwc/pcie-histb,controller/dwc/pcie-intel-gw,controller/dwc/pcie-keembay,controller/dwc/pcie-kirin,controller/dwc/pcie-nxp-s32g,controller/dwc/pcie-qcom,controller/dwc/pcie-qcom-common,controller/dwc/pcie-qcom-ep,controller/dwc/pcie-rcar-gen4,controller/dwc/pcie-sophgo,controller/dwc/pcie-spacemit-k1,controller/dwc/pcie-spear13xx,controller/dwc/pcie-stm32,controller/dwc/pcie-stm32-ep,controller/dwc/pcie-tegra194,controller/dwc/pcie-tegra194-acpi,controller/dwc/pcie-uniphier,controller/dwc/pcie-uniphier-ep,controller/dwc/pcie-visconti,controller/mobiveil/pcie-layerscape-gen4,controller/mobiveil/pcie-mobiveil,controller/mobiveil/pcie-mobiveil-host,controller/mobiveil/pcie-mobiveil-plat,controller/pci-aardvark,controller/pci-ftpci100,controller/pci-host-common,controller/pci-host-generic,controller/pci-hyperv,controller/pci-hyperv-intf,controller/pci-ixp4xx,controller/pci-loongson,controller/pci-mvebu,controller/pci-rcar-gen2,controller/pci-tegra,controller/pci-thunder-ecam,controller/pci-thunder-pem,controller/pci-v3-semi,controller/pci-versatile,controller/pci-xgene,controller/pci-xgene-msi,controller/pcie-altera,controller/pcie-altera-msi,controller/pcie-apple,controller/pcie-aspeed,controller/pcie-brcmstb,controller/pcie-hisi-error,controller/pcie-iproc,controller/pcie-iproc-bcma,controller/pcie-iproc-msi,controller/pcie-iproc-platform,controller/pcie-mediatek,controller/pcie-mediatek-gen3,controller/pcie-mt7621,controller/pcie-rcar,controller/pcie-rcar-ep,controller/pcie-rcar-host,controller/pcie-rockchip,controller/pcie-rockchip-ep,controller/pcie-rockchip-host,controller/pcie-rzg3s-host,controller/pcie-xilinx,controller/pcie-xilinx-cpm,controller/pcie-xilinx-dma-pl,controller/pcie-xilinx-nwl,controller/plda/pcie-microchip-host,controller/plda/pcie-plda-host,controller/plda/pcie-starfive,controller/vmd,devres,doe,endpoint/functions/pci-epf-mhi,endpoint/functions/pci-epf-ntb,endpoint/functions/pci-epf-vntb,endpoint/pci-ep-cfs,endpoint/pci-ep-msi,endpoint/pci-epc-core,endpoint/pci-epc-mem,endpoint/pci-epf-core,host-bridge,hotplug/acpi_pcihp,hotplug/acpiphp_ampere_altra,hotplug/acpiphp_core,hotplug/acpiphp_glue,hotplug/acpiphp_ibm,hotplug/cpci_hotplug_core,hotplug/cpci_hotplug_pci,hotplug/cpcihp_generic,hotplug/cpcihp_zt5550,hotplug/cpqphp_core,hotplug/cpqphp_ctrl,hotplug/cpqphp_nvram,hotplug/cpqphp_pci,hotplug/cpqphp_sysfs,hotplug/ibmphp_core,hotplug/ibmphp_ebda,hotplug/ibmphp_hpc,hotplug/ibmphp_pci,hotplug/ibmphp_res,hotplug/octep_hp,hotplug/pci_hotplug_core,hotplug/pciehp_core,hotplug/pciehp_ctrl,hotplug/pciehp_hpc,hotplug/pciehp_pci,hotplug/pnv_php,hotplug/rpadlpar_core,hotplug/rpadlpar_sysfs,hotplug/rpaphp_core,hotplug/rpaphp_pci,hotplug/rpaphp_slot,hotplug/s390_pci_hpc,hotplug/shpchp_core,hotplug/shpchp_ctrl,hotplug/shpchp_hpc,hotplug/shpchp_pci,hotplug/shpchp_sysfs,ide,iomap,iov,irq,mmap,npem,of,of_property,p2pdma,pci,pci-acpi,pci-bridge-emul,pci-label,pci-mid,pci-pf-stub,pci-stub,pci-sysfs,pcie/aer,pcie/aer_cxl_rch,pcie/aer_inject,pcie/aspm,pcie/bwctrl,pcie/dpc,pcie/edr,pcie/err,pcie/pme,pcie/portdrv,pcie/ptm,pcie/rcec,pcie/tlp,proc,pwrctrl/core,pwrctrl/generic,pwrctrl/pci-pwrctrl-pwrseq,pwrctrl/pci-pwrctrl-tc9563,quirks,rebar,remove,rom,search,setup-bus,setup-cardbus,setup-res,slot,switch/switchtec,syscall,tph,trace,tsm,vc,vgaarb,vpd,xen-pcifront}.c`

/// Number of Linux `.c` files catalogued for this subsystem.
pub const PCI_SOURCES_COUNT: usize = 202;

/// Catalogued upstream Linux source paths used as PCI source truth.
pub const PCI_SOURCES: &[&str] = &[
    "vendor/linux/drivers/pci/access.c",
    "vendor/linux/drivers/pci/ats.c",
    "vendor/linux/drivers/pci/controller/cadence/pci-j721e.c",
    "vendor/linux/drivers/pci/controller/cadence/pci-sky1.c",
    "vendor/linux/drivers/pci/controller/cadence/pcie-cadence.c",
    "vendor/linux/drivers/pci/controller/cadence/pcie-cadence-ep.c",
    "vendor/linux/drivers/pci/controller/cadence/pcie-cadence-host.c",
    "vendor/linux/drivers/pci/controller/cadence/pcie-cadence-host-common.c",
    "vendor/linux/drivers/pci/controller/cadence/pcie-cadence-host-hpa.c",
    "vendor/linux/drivers/pci/controller/cadence/pcie-cadence-hpa.c",
    "vendor/linux/drivers/pci/controller/cadence/pcie-cadence-plat.c",
    "vendor/linux/drivers/pci/controller/cadence/pcie-sg2042.c",
    "vendor/linux/drivers/pci/controller/dwc/pci-dra7xx.c",
    "vendor/linux/drivers/pci/controller/dwc/pci-exynos.c",
    "vendor/linux/drivers/pci/controller/dwc/pci-imx6.c",
    "vendor/linux/drivers/pci/controller/dwc/pci-keystone.c",
    "vendor/linux/drivers/pci/controller/dwc/pci-layerscape.c",
    "vendor/linux/drivers/pci/controller/dwc/pci-layerscape-ep.c",
    "vendor/linux/drivers/pci/controller/dwc/pci-meson.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-al.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-amd-mdb.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-andes-qilai.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-armada8k.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-artpec6.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-designware.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-designware-debugfs.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-designware-ep.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-designware-host.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-designware-plat.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-dw-rockchip.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-eswin.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-fu740.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-hisi.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-histb.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-intel-gw.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-keembay.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-kirin.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-nxp-s32g.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-qcom.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-qcom-common.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-qcom-ep.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-rcar-gen4.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-sophgo.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-spacemit-k1.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-spear13xx.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-stm32.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-stm32-ep.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-tegra194.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-tegra194-acpi.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-uniphier.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-uniphier-ep.c",
    "vendor/linux/drivers/pci/controller/dwc/pcie-visconti.c",
    "vendor/linux/drivers/pci/controller/mobiveil/pcie-layerscape-gen4.c",
    "vendor/linux/drivers/pci/controller/mobiveil/pcie-mobiveil.c",
    "vendor/linux/drivers/pci/controller/mobiveil/pcie-mobiveil-host.c",
    "vendor/linux/drivers/pci/controller/mobiveil/pcie-mobiveil-plat.c",
    "vendor/linux/drivers/pci/controller/pci-aardvark.c",
    "vendor/linux/drivers/pci/controller/pci-ftpci100.c",
    "vendor/linux/drivers/pci/controller/pci-host-common.c",
    "vendor/linux/drivers/pci/controller/pci-host-generic.c",
    "vendor/linux/drivers/pci/controller/pci-hyperv.c",
    "vendor/linux/drivers/pci/controller/pci-hyperv-intf.c",
    "vendor/linux/drivers/pci/controller/pci-ixp4xx.c",
    "vendor/linux/drivers/pci/controller/pci-loongson.c",
    "vendor/linux/drivers/pci/controller/pci-mvebu.c",
    "vendor/linux/drivers/pci/controller/pci-rcar-gen2.c",
    "vendor/linux/drivers/pci/controller/pci-tegra.c",
    "vendor/linux/drivers/pci/controller/pci-thunder-ecam.c",
    "vendor/linux/drivers/pci/controller/pci-thunder-pem.c",
    "vendor/linux/drivers/pci/controller/pci-v3-semi.c",
    "vendor/linux/drivers/pci/controller/pci-versatile.c",
    "vendor/linux/drivers/pci/controller/pci-xgene.c",
    "vendor/linux/drivers/pci/controller/pci-xgene-msi.c",
    "vendor/linux/drivers/pci/controller/pcie-altera.c",
    "vendor/linux/drivers/pci/controller/pcie-altera-msi.c",
    "vendor/linux/drivers/pci/controller/pcie-apple.c",
    "vendor/linux/drivers/pci/controller/pcie-aspeed.c",
    "vendor/linux/drivers/pci/controller/pcie-brcmstb.c",
    "vendor/linux/drivers/pci/controller/pcie-hisi-error.c",
    "vendor/linux/drivers/pci/controller/pcie-iproc.c",
    "vendor/linux/drivers/pci/controller/pcie-iproc-bcma.c",
    "vendor/linux/drivers/pci/controller/pcie-iproc-msi.c",
    "vendor/linux/drivers/pci/controller/pcie-iproc-platform.c",
    "vendor/linux/drivers/pci/controller/pcie-mediatek.c",
    "vendor/linux/drivers/pci/controller/pcie-mediatek-gen3.c",
    "vendor/linux/drivers/pci/controller/pcie-mt7621.c",
    "vendor/linux/drivers/pci/controller/pcie-rcar.c",
    "vendor/linux/drivers/pci/controller/pcie-rcar-ep.c",
    "vendor/linux/drivers/pci/controller/pcie-rcar-host.c",
    "vendor/linux/drivers/pci/controller/pcie-rockchip.c",
    "vendor/linux/drivers/pci/controller/pcie-rockchip-ep.c",
    "vendor/linux/drivers/pci/controller/pcie-rockchip-host.c",
    "vendor/linux/drivers/pci/controller/pcie-rzg3s-host.c",
    "vendor/linux/drivers/pci/controller/pcie-xilinx.c",
    "vendor/linux/drivers/pci/controller/pcie-xilinx-cpm.c",
    "vendor/linux/drivers/pci/controller/pcie-xilinx-dma-pl.c",
    "vendor/linux/drivers/pci/controller/pcie-xilinx-nwl.c",
    "vendor/linux/drivers/pci/controller/plda/pcie-microchip-host.c",
    "vendor/linux/drivers/pci/controller/plda/pcie-plda-host.c",
    "vendor/linux/drivers/pci/controller/plda/pcie-starfive.c",
    "vendor/linux/drivers/pci/controller/vmd.c",
    "vendor/linux/drivers/pci/devres.c",
    "vendor/linux/drivers/pci/doe.c",
    "vendor/linux/drivers/pci/endpoint/functions/pci-epf-mhi.c",
    "vendor/linux/drivers/pci/endpoint/functions/pci-epf-ntb.c",
    "vendor/linux/drivers/pci/endpoint/functions/pci-epf-vntb.c",
    "vendor/linux/drivers/pci/endpoint/pci-ep-cfs.c",
    "vendor/linux/drivers/pci/endpoint/pci-ep-msi.c",
    "vendor/linux/drivers/pci/endpoint/pci-epc-core.c",
    "vendor/linux/drivers/pci/endpoint/pci-epc-mem.c",
    "vendor/linux/drivers/pci/endpoint/pci-epf-core.c",
    "vendor/linux/drivers/pci/host-bridge.c",
    "vendor/linux/drivers/pci/hotplug/acpi_pcihp.c",
    "vendor/linux/drivers/pci/hotplug/acpiphp_ampere_altra.c",
    "vendor/linux/drivers/pci/hotplug/acpiphp_core.c",
    "vendor/linux/drivers/pci/hotplug/acpiphp_glue.c",
    "vendor/linux/drivers/pci/hotplug/acpiphp_ibm.c",
    "vendor/linux/drivers/pci/hotplug/cpci_hotplug_core.c",
    "vendor/linux/drivers/pci/hotplug/cpci_hotplug_pci.c",
    "vendor/linux/drivers/pci/hotplug/cpcihp_generic.c",
    "vendor/linux/drivers/pci/hotplug/cpcihp_zt5550.c",
    "vendor/linux/drivers/pci/hotplug/cpqphp_core.c",
    "vendor/linux/drivers/pci/hotplug/cpqphp_ctrl.c",
    "vendor/linux/drivers/pci/hotplug/cpqphp_nvram.c",
    "vendor/linux/drivers/pci/hotplug/cpqphp_pci.c",
    "vendor/linux/drivers/pci/hotplug/cpqphp_sysfs.c",
    "vendor/linux/drivers/pci/hotplug/ibmphp_core.c",
    "vendor/linux/drivers/pci/hotplug/ibmphp_ebda.c",
    "vendor/linux/drivers/pci/hotplug/ibmphp_hpc.c",
    "vendor/linux/drivers/pci/hotplug/ibmphp_pci.c",
    "vendor/linux/drivers/pci/hotplug/ibmphp_res.c",
    "vendor/linux/drivers/pci/hotplug/octep_hp.c",
    "vendor/linux/drivers/pci/hotplug/pci_hotplug_core.c",
    "vendor/linux/drivers/pci/hotplug/pciehp_core.c",
    "vendor/linux/drivers/pci/hotplug/pciehp_ctrl.c",
    "vendor/linux/drivers/pci/hotplug/pciehp_hpc.c",
    "vendor/linux/drivers/pci/hotplug/pciehp_pci.c",
    "vendor/linux/drivers/pci/hotplug/pnv_php.c",
    "vendor/linux/drivers/pci/hotplug/rpadlpar_core.c",
    "vendor/linux/drivers/pci/hotplug/rpadlpar_sysfs.c",
    "vendor/linux/drivers/pci/hotplug/rpaphp_core.c",
    "vendor/linux/drivers/pci/hotplug/rpaphp_pci.c",
    "vendor/linux/drivers/pci/hotplug/rpaphp_slot.c",
    "vendor/linux/drivers/pci/hotplug/s390_pci_hpc.c",
    "vendor/linux/drivers/pci/hotplug/shpchp_core.c",
    "vendor/linux/drivers/pci/hotplug/shpchp_ctrl.c",
    "vendor/linux/drivers/pci/hotplug/shpchp_hpc.c",
    "vendor/linux/drivers/pci/hotplug/shpchp_pci.c",
    "vendor/linux/drivers/pci/hotplug/shpchp_sysfs.c",
    "vendor/linux/drivers/pci/ide.c",
    "vendor/linux/drivers/pci/iomap.c",
    "vendor/linux/drivers/pci/iov.c",
    "vendor/linux/drivers/pci/irq.c",
    "vendor/linux/drivers/pci/mmap.c",
    "vendor/linux/drivers/pci/npem.c",
    "vendor/linux/drivers/pci/of.c",
    "vendor/linux/drivers/pci/of_property.c",
    "vendor/linux/drivers/pci/p2pdma.c",
    "vendor/linux/drivers/pci/pci.c",
    "vendor/linux/drivers/pci/pci-acpi.c",
    "vendor/linux/drivers/pci/pci-bridge-emul.c",
    "vendor/linux/drivers/pci/pci-label.c",
    "vendor/linux/drivers/pci/pci-mid.c",
    "vendor/linux/drivers/pci/pci-pf-stub.c",
    "vendor/linux/drivers/pci/pci-stub.c",
    "vendor/linux/drivers/pci/pci-sysfs.c",
    "vendor/linux/drivers/pci/pcie/aer.c",
    "vendor/linux/drivers/pci/pcie/aer_cxl_rch.c",
    "vendor/linux/drivers/pci/pcie/aer_inject.c",
    "vendor/linux/drivers/pci/pcie/aspm.c",
    "vendor/linux/drivers/pci/pcie/bwctrl.c",
    "vendor/linux/drivers/pci/pcie/dpc.c",
    "vendor/linux/drivers/pci/pcie/edr.c",
    "vendor/linux/drivers/pci/pcie/err.c",
    "vendor/linux/drivers/pci/pcie/pme.c",
    "vendor/linux/drivers/pci/pcie/portdrv.c",
    "vendor/linux/drivers/pci/pcie/ptm.c",
    "vendor/linux/drivers/pci/pcie/rcec.c",
    "vendor/linux/drivers/pci/pcie/tlp.c",
    "vendor/linux/drivers/pci/proc.c",
    "vendor/linux/drivers/pci/pwrctrl/core.c",
    "vendor/linux/drivers/pci/pwrctrl/generic.c",
    "vendor/linux/drivers/pci/pwrctrl/pci-pwrctrl-pwrseq.c",
    "vendor/linux/drivers/pci/pwrctrl/pci-pwrctrl-tc9563.c",
    "vendor/linux/drivers/pci/quirks.c",
    "vendor/linux/drivers/pci/rebar.c",
    "vendor/linux/drivers/pci/remove.c",
    "vendor/linux/drivers/pci/rom.c",
    "vendor/linux/drivers/pci/search.c",
    "vendor/linux/drivers/pci/setup-bus.c",
    "vendor/linux/drivers/pci/setup-cardbus.c",
    "vendor/linux/drivers/pci/setup-res.c",
    "vendor/linux/drivers/pci/slot.c",
    "vendor/linux/drivers/pci/switch/switchtec.c",
    "vendor/linux/drivers/pci/syscall.c",
    "vendor/linux/drivers/pci/tph.c",
    "vendor/linux/drivers/pci/trace.c",
    "vendor/linux/drivers/pci/tsm.c",
    "vendor/linux/drivers/pci/vc.c",
    "vendor/linux/drivers/pci/vgaarb.c",
    "vendor/linux/drivers/pci/vpd.c",
    "vendor/linux/drivers/pci/xen-pcifront.c",
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn count_matches_table() {
        assert_eq!(PCI_SOURCES.len(), PCI_SOURCES_COUNT);
    }

    #[test]
    fn all_paths_have_canonical_prefix() {
        for path in PCI_SOURCES {
            assert!(path.starts_with("vendor/linux/drivers/pci/"), "{path}");
            assert!(path.ends_with(".c"));
        }
    }
}
